<?php
// Setup
define('FRA_Version','3.3_2023-06-10');
define('FRA_Konfiguration','Grundkonfiguration');
define('FRA_WarnMeldungen',false);
define('FRA_Www','localhost');
define('FRA_Pfad','/var/www/html/');
define('FRA_Daten','daten/');
define('FRA_Bilder','bilder/');
define('FRA_UploadDir','bilder/');
define('FRA_Fragen','fragen.txt');
define('FRA_Folgen','testfolgen.txt');
define('FRA_Ergebnis','ergebnis.csv');
define('FRA_Nutzer','nutzer00.txt');
define('FRA_Zuweisung','zuweisungen.txt');
define('FRA_SQL',true);
define('FRA_SqlHost','mysql');
define('FRA_SqlDaBa','testfragen');
define('FRA_SqlUser','root');
define('FRA_SqlPass','root');
define('FRA_SqlTabF','fra_fragen');
define('FRA_SqlTabE','fra_ergebnis');
define('FRA_SqlTabN','fra_nutzer');
define('FRA_SqlTabT','fra_folgen');
define('FRA_SqlTabZ','fra_zuweisungen');
define('FRA_Schluessel','00');

// Administration
define('ADF_MitLogin',false);
define('ADF_Admin','admin');
define('ADF_Passwort','');
define('ADF_AuthLogin',false);
define('ADF_Author','author');
define('ADF_AuthPass','');
define('ADF_SessionsAgent',true);
define('ADF_SessionsIPAddr',true);
define('ADF_Hilfe','http://www.server-scripts.de/testfragen/');
define('ADF_Breite',990);
define('ADF_CKEditor',false);
define('ADF_AntwortZahl',6);
define('ADF_AnmerkZahl',1);
define('ADF_FragenFeldHoehe',5);
define('ADF_AntwortFeldHoehe',2);
define('ADF_AnmerkFeldHoehe',3);
define('ADF_StripSlashes',false);
define('ADF_ListenLaenge',25);
define('ADF_Rueckwaerts',false);
define('ADF_ErgebnisLaenge',10);
define('ADF_ErgebnisRueckw',true);
define('ADF_NutzerLaenge',15);
define('ADF_NutzerRueckw',false);
define('ADF_NutzerBetreff','Ihr Testergebnis');
define('ADF_NutzerKontakt','Sehr geehrte Damen und Herren,\n \n Sie haben im Testfragen-Script.....');
define('ADF_DruckSuch','');
define('ADF_DruckFeld','1;0;0;1;1;1;1;0;1;1');

//Allgemeines
define('FRA_Schablone','fraSeite.htm');
define('FRA_CSSDatei','fraStyle.css');
define('FRA_LayoutTyp',2);
define('FRA_LayoutBildText',true);
define('FRA_DivTextWidth',420);
define('FRA_ResponsiveLayout',false);
define('FRA_LayoutReservePixel',10);
define('FRA_Rahmen',false);
define('FRA_ProSeite',1);
define('FRA_RadioButton',false);
define('FRA_SofortBeiKlick',0);
define('FRA_BildErsatz','fragezeichen.jpg');
define('FRA_NummerStellen','03');
define('FRA_Zeichensatz',0); //0:Standard 1:HTML-&-maskiert 2:UTF-8
define('FRA_ZeichnsNorm',0);
define('FRA_TimeZoneSet','Europe/Berlin');
define('FRA_SqlCharSet','');
define('FRA_Datumsformat','d.m.y H:i');
define('FRA_Dezimalzeichen',',');
define('FRA_FolgeName','');
define('FRA_FolgeSpontan','');
define('FRA_KategorieFilter',"");
define('FRA_AuchInaktive',false);
define('FRA_AuchVersteckte',false);
define('FRA_WenigerFragen',0);
define('FRA_Zufallsfolge',true);
define('FRA_MischKategorie',true);
define('FRA_ZeitLimit',0);
define('FRA_RestZeit',false);
define('FRA_Rueckwaerts',false);
define('FRA_Auslassen',true);
define('FRA_ZufallsAntwort',false);
define('FRA_PruefeAnzahl',false);
define('FRA_PruefeAntw',false);
define('FRA_AntwortVersuche',0); //0:unendlich
define('FRA_PunkteTeilen',true);
define('FRA_Offenlegen',false);
define('FRA_OffenNurFalsche',true);
define('FRA_LernModus',false);
define('FRA_ZeigeNummer','unten');
define('FRA_NummernTyp',0);
define('FRA_ZeigeKategorie','oben');
define('FRA_ZeigeBemerkung','');
define('FRA_HilfeBemerkung',false);
define('FRA_LernBemerkung',0);
define('FRA_ZeigeNamen','');
define('FRA_ZeigeAntwZahl',true);
define('FRA_ZeigePunkte','1');
define('FRA_ZeigeVersuche','');
define('FRA_SchalterSuchen','Frage suchen');
define('FRA_SchalterTxGeheZu','');
define('FRA_SchalterZurueck','zur�ck bl�ttern');
define('FRA_SchalterTxZurueck','');
define('FRA_Schalter2Zeilen',false);
define('FRA_FertigHtml',true);
define('FRA_MaxSessionZeit',90);
define('FRA_DSELink','datenschutz.html');
define('FRA_DSETarget','_blank');
define('FRA_DSEPopUp',false);
define('FRA_DSEPopupW',900);
define('FRA_DSEPopupH',600);
define('FRA_DSEPopupX',5);
define('FRA_DSEPopupY',5);
define('FRA_Captcha',true);
define('CAPTCHA_SALT','J33516');
define('FRA_CaptchaTyp','G');
define('FRA_CaptchaGrafisch',true);
define('FRA_CaptchaNumerisch',false);
define('FRA_CaptchaTextlich',false);
define('FRA_CaptchaPfad','captcha/');
define('FRA_CaptchaDatei','captcha.csv');
define('FRA_CaptchaHgFarb','#F3F3F3');
define('FRA_CaptchaTxFarb','#880000');
define('FRA_Empfaenger',"webmaster@domain.de");
define('FRA_Sender','Testfragen-Script <webmaster@domain.de>');
define('FRA_Smtp',false);
define('FRA_SmtpHost','localhost');
define('FRA_SmtpPort',25);
if(!defined('SMTP_No_TLS')) define('SMTP_No_TLS',true);
define('FRA_SmtpAuth',false);
define('FRA_SmtpUser','');
define('FRA_SmtpPass','');
define('FRA_EnvelopeSender','');

//Eingabe
define('FRA_Kategorien',"Verhalten;Gefahrenlehre;Vorfahrt;Verkehrszeichen");
define('FRA_MehrfachKat',false);
define('FRA_OhneAntwort',false);
define('FRA_BildKB',150);
define('FRA_BildW',250);
define('FRA_BildH',180);

//Druckeinstellungen
define('FRA_Drucken','');
define('FRA_DruckSchablone','fraSeite.htm');
define('FRA_DruckSpalten','1;0;1;0;1;0;1;0;0'); // Nr;Kat;Fra;Loe;Pkt;Bld;Aw;B1;B2
define('FRA_DruckSuchSpalten',3);
define('FRA_DruckSuche','1;0;1;0;0;0;1;0;0');
define('FRA_DruckRueckw',false);
define('FRA_DruckZufallsAw',false);
define('FRA_DruckBildW',100);
define('FRA_DruckGast',false);

//Teilnehmerregistrierung
define('FRA_Registrierung','nachher'); // '', 'vorher' oder 'nachher'
define('FRA_RegistWenn','');
define('FRA_RegistGrenze',60);
define('FRA_TeilnehmerSperre',false);
define('FRA_NachRegisterWohin','Daten');
define('FRA_TeilnehmerMitCode',false);
define('FRA_TeilnehmerDSE1',false);
define('FRA_TeilnehmerDSE2',false);
define('FRA_TeilnehmerStandardtest',false);
define('FRA_TeilnehmerSpontaneFolge',false);
define('FRA_TeilnehmerAlleFolgen',true);
define('FRA_TeilnehmerDrucken',false);
define('FRA_TeilnehmerKennfeld',1);
define('FRA_SofortFrageNachReg',false);
define('FRA_TeilnehmerFelder',"Name;Vorname;e-Mail;Telefon, Mobil");
define('FRA_TeilnehmerPflicht',"1;0;0;0");

//Benutzerverwaltung
define('FRA_Nutzerverwaltung','');
define('FRA_LoginWenn','');
define('FRA_LoginGrenze',50);
define('FRA_Nutzerzwang',false);
define('FRA_NutzerSperre',false);
define('FRA_NutzerMitCode',false);
define('FRA_NutzerFelder',"Nummer;aktiv;Benutzer;Passwort;e-Mail;Anrede;Vorname + Name;PLZ Ort;Strasse;Telefon, Mobil;Fax");
define('FRA_NutzerPflicht',"0;0;1;1;1;0;1;1;0;0;0");
define('FRA_NutzerFrist',0);
define('FRA_Nutzerfreigabe',false);
define('FRA_NutzerNeuErlaubt',true);
define('FRA_NutzerNeuAdmMail',true);
define('FRA_NutzerNeuMail',true);
define('FRA_NutzerAktivMail',true);
define('FRA_PasswortSenden',true);
define('FRA_NutzerDSE1',false);
define('FRA_NutzerDSE2',false);
define('FRA_NachLoginWohin','FragenA'); //DatenBest,DatenKorr,Fragen,Zentrum
define('FRA_NutzerTests',false);

//Benutzerzentrum
define('FRA_NutzerStandardtest',true);
define('FRA_NutzerAlleFolgen',false);
define('FRA_NutzerSpontaneFolge',false);
define('FRA_NutzerErgebnis',true);
define('FRA_NutzerLoesung',false);
define('FRA_NutzerLsgAlle',true);
define('FRA_NutzerStatistik',true);
define('FRA_NutzerAendern',true);
define('FRA_ZntErgebnisRueckw',true);
define('FRA_ZntAntwort',true);
define('FRA_ZntLoesung',true);
define('FRA_ZntAnzahlO',true);
define('FRA_ZntZeitO',true);
define('FRA_ZntRichtigeO',true);
define('FRA_ZntFalscheO',true);
define('FRA_ZntPunkteO',true);
define('FRA_ZntVerbalO',false);
define('FRA_ZntVersucheO',false);
define('FRA_ZntAuslassenO',false);
define('FRA_ZntFrageNr',true);
define('FRA_ZntErgebnis',true);
define('FRA_ZntPunkte',true);
define('FRA_ZntVersuche',false);
define('FRA_ZntAuslassen',false);
define('FRA_ZntKatErgebnis',false);
define('FRA_ZntKatFehlErgb',false);
define('FRA_ZntKatPunkte',false);
define('FRA_ZntKatSumme',true);

//Ergebnisbewertung
define('FRA_PositivWertung',true);
define('FRA_TeilWertung',1);
define('FRA_DatSpeichern',true);
define('FRA_DatAnzahlO',true);
define('FRA_DatZeitO',true);
define('FRA_DatRichtigeO',true);
define('FRA_DatFalscheO',true);
define('FRA_DatPunkteO',true);
define('FRA_TxZeigeAdmPkte','');
define('FRA_DatVerbalO',false);
define('FRA_DatVerbalL',false);
define('FRA_DatVersucheO',true);
define('FRA_DatAuslassenO',true);
define('FRA_DatPersonL',true);
define('FRA_DatPersonD',false);
define('FRA_DatPersonN','');
define('FRA_DatPersonT','');
define('FRA_DatFrageNr',true);
define('FRA_DatErgebnis',true);
define('FRA_DatPunkte',true);
define('FRA_DatVersuche',true);
define('FRA_DatAuslassen',true);
define('FRA_DatAntwort',true);
define('FRA_DatVerlauf',true);
define('FRA_DatKatErgebnis',false);
define('FRA_DatKatFehlErgb',true);
define('FRA_DatKatPunkte',false);
define('FRA_DatKatSumme',true);
define('FRA_ErgDruckTempl',true);
define('FRA_TxErgDruckKopf',"Ergebnis Nr. #N von Teilnehmer #T am #D");
define('FRA_TxErgDruckFuss',"Gesamt #P von #G Punkten, #W Prozent");
define('FRA_VerbalPunkte',true);
define('FRA_VerbalAb1',50);
define('FRA_VerbalTx1',"bestanden");
define('FRA_VerbalAb2',0);
define('FRA_VerbalTx2',"");
define('FRA_VerbalAb3',0);
define('FRA_VerbalTx3',"");
define('FRA_VerbalAb4',0);
define('FRA_VerbalTx4',"");
define('FRA_VerbalAb5',0);
define('FRA_VerbalTx5',"");
define('FRA_VerbalAb6',0);
define('FRA_VerbalTx6',"");
define('FRA_VerbalTx0',"nicht bestanden");

//Bildschirmauswertung
define('FRA_BewertungsSeite',true);
define('FRA_LoesungsSeite',false);
define('FRA_LoesungsFalsche',true);
define('FRA_LoesungsAnmk',false);
define('FRA_BldVorAw',false);
define('FRA_BldNachAw',false);
define('FRA_TlnVorAw',false);
define('FRA_TlnNachAw',false);
define('FRA_BldAnzahlO',true);
define('FRA_BldZeitO',true);
define('FRA_BldRichtigeO',true);
define('FRA_BldFalscheO',true);
define('FRA_BldPunkteO',true);
define('FRA_BldVerbalO',false);
define('FRA_BldVersucheO',true);
define('FRA_BldAuslassenO',true);
define('FRA_BldAlleNr',true);
define('FRA_BldErgebnis',true);
define('FRA_BldTestName',true);
define('FRA_BldPunkte',true);
define('FRA_BldVersuche',true);
define('FRA_BldAuslassen',true);
define('FRA_BldKatErgebnis',false);
define('FRA_BldKatFehlErgb',false);
define('FRA_BldKatPunkte',false);
define('FRA_BldKatSumme',true);
define('FRA_BldAnzahlU',true);
define('FRA_BldZeitU',true);
define('FRA_BldRichtigeU',true);
define('FRA_BldFalscheU',true);
define('FRA_BldPunkteU',true);
define('FRA_BldVerbalU',false);
define('FRA_BldVersucheU',true);
define('FRA_BldAuslassenU',true);

//Administrator-e-Mail
define('FRA_AdmBetreff',"Frage-Antwort - Ergebnis");
define('FRA_AdmVorspann',"Ergebnis:");
define('FRA_AdmAbspann','- Ende -');
define('FRA_AdmPersonO',true);
define('FRA_AdmAnzahlO',true);
define('FRA_AdmZeitO',true);
define('FRA_AdmRichtigeO',true);
define('FRA_AdmFalscheO',true);
define('FRA_AdmPunkteO',true);
define('FRA_AdmVerbalO',false);
define('FRA_AdmVersucheO',true);
define('FRA_AdmAuslassenO',true);
define('FRA_AdmAlleNr',true);
define('FRA_AdmErgebnis',true);
define('FRA_AdmTestName',true);
define('FRA_AdmPunkte',true);
define('FRA_AdmVersuche',true);
define('FRA_AdmAuslassen',true);
define('FRA_AdmKatErgebnis',false);
define('FRA_AdmKatFehlErgb',false);
define('FRA_AdmKatPunkte',false);
define('FRA_AdmKatSumme',true);
define('FRA_AdmAnzahlU',true);
define('FRA_AdmZeitU',true);
define('FRA_AdmRichtigeU',true);
define('FRA_AdmFalscheU',true);
define('FRA_AdmPunkteU',true);
define('FRA_AdmVerbalU',false);
define('FRA_AdmVersucheU',true);
define('FRA_AdmAuslassenU',true);
define('FRA_AdmAntwort',true);
define('FRA_AdmVerlauf',true);
define('FRA_AdmPersonU',true);

//Teilnehmer-e-Mail
define('FRA_TlnBetreff',"Testfragen-Script - Ergebnis");
define('FRA_TlnVorspann','Sehr geehrte Damen und Herren,\n \n Sie haben soeben das Testfragen-Script benutzt und dabei folgendes Resultat erreicht:');
define('FRA_TlnAbspann','Vielen Dank f�r Ihre Teilnahme\n (automatische Benachrichtigung)');
define('FRA_TlnPersonO',true);
define('FRA_TlnAnzahlO',true);
define('FRA_TlnZeitO',true);
define('FRA_TlnRichtigeO',true);
define('FRA_TlnFalscheO',true);
define('FRA_TlnPunkteO',true);
define('FRA_TlnVerbalO',false);
define('FRA_TlnVersucheO',true);
define('FRA_TlnAuslassenO',true);
define('FRA_TlnAlleNr',true);
define('FRA_TlnErgebnis',true);
define('FRA_TlnTestName',true);
define('FRA_TlnPunkte',true);
define('FRA_TlnVersuche',true);
define('FRA_TlnAuslassen',true);
define('FRA_TlnKatErgebnis',false);
define('FRA_TlnKatFehlErgb',false);
define('FRA_TlnKatPunkte',false);
define('FRA_TlnKatSumme',true);
define('FRA_TlnAnzahlU',true);
define('FRA_TlnZeitU',true);
define('FRA_TlnRichtigeU',true);
define('FRA_TlnFalscheU',true);
define('FRA_TlnPunkteU',true);
define('FRA_TlnVerbalU',false);
define('FRA_TlnVersucheU',true);
define('FRA_TlnAuslassenU',true);
define('FRA_TlnAntwort',true);
define('FRA_TlnVerlauf',true);
define('FRA_TlnPersonU',true);

// Statistik/Bestenliste
define('FRA_Statistik',true);
define('FRA_StatOffen',true);
define('FRA_StatFelder','1,2,0,0,0,0,4,0,0,0,0,0,0,3');
define('FRA_StatNFelder','1,2,0,0,0,0,4,0,0,0,0,0,0,3');
define('FRA_StatCssStil',',,,,,,font-weight:bold;,,,,,,,');
define('FRA_StatTlnFld','1,1');
define('FRA_StatNtzFld','0,0,0,0,0,1,1');
define('FRA_StatTlnTrn',', ');
define('FRA_StatNtzTrn',', ');
define('FRA_StatSortier1',6);
define('FRA_StatSortier2',2);
define('FRA_StatSortAbsteig',true);
define('FRA_StatSrt2Absteig',true);
define('FRA_StatDatumZeit',true);
define('FRA_StatKommaStellen',1);
define('FRA_StatListenZeilen',20);

/* Sprachfloskeln */
// feste Begriffe
define('FRA_TxNr','Nr.');
define('FRA_TxVon','von');
define('FRA_TxFuer','f�r');
define('FRA_TxOder','oder');
define('FRA_TxNicht','nicht');
define('FRA_TxBis','bis');
define('FRA_TxWie','wie');
define('FRA_TxOderWie','oder wie');
define('FRA_TxIstOderAb','ist oder ab');
define('FRA_TxAberNichtWie','aber nicht wie');
define('FRA_TxDatum','Datum/Zeit');
define('FRA_TxZeit','Zeit');
define('FRA_TxFrage','Frage');
define('FRA_TxVorFrage',"[color=navy][b]Frage[/b][/color]:");
define('FRA_TxAntwort','Antwort');
define('FRA_TxLoesung','L�sung');
define('FRA_TxErgebnis','Ergebnis');
define('FRA_TxPunkte','Punkte');
define('FRA_TxAnzahl','Fragenanzahl');
define('FRA_TxKategorie','Kategorie:');
define('FRA_TxBild','Bild');
define('FRA_TxBemerkung','Anmerkung');
define('FRA_TxRichtig','richtig');
define('FRA_TxFalsch','falsch');
define('FRA_TxAktiv','aktiviert');
define('FRA_TxWeiter','Weiter');
define('FRA_TxEintragen','Eintragen');
define('FRA_TxNaechste','n�chste Frage');
define('FRA_TxAntworte','Frage beantworten');
define('FRA_TxRichtige','richtige Antworten');
define('FRA_TxFalsche','falsche Antworten');
define('FRA_TxVersuche','Antwortversuche');
define('FRA_TxAuslassen','Auslassungen');
define('FRA_TxPflicht','Pflichtfeld');
define('FRA_TxAntwSq','Antwortsequenz');
define('FRA_TxLaufSq','Durchlaufsequenz');
define('FRA_TxCaptchaFeld','Sicherheitscode');
define('FRA_TxCaptchaNeu','neues #Captcha anfordern');
define('FRA_TxZahlenCaptcha','Zahlen-');
define('FRA_TxTextCaptcha','Text-');
define('FRA_TxGrafikCaptcha','Grafik-');
define('FRA_TxCaptchaHilfe','Bitte den Buchstaben und die 4 Ziffern �bertragen');
define('FRA_TxCaptchaFehl','Bitte geben Sie den Sicherheitscode korrekt ein!');

//Durchlaufmeldungen
define('FRA_TxBeginn',"Beginnen Sie jetzt mit dem Beantworten der #Z Fragen.");
define('FRA_TxNormal',"Frage Nummer #N");
define('FRA_TxZwischenwertung',"");
define('FRA_TxHandle',"Bitte beantworten Sie die Frage #N!");
define('FRA_TxStimmt',"Die Frage #N wurde richtig beantwortet.");
define('FRA_TxHalb',"Die Anzahl der Antworten zur Frage #N stimmt nicht.");
define('FRA_TxNochMal',"Die Frage #N wurde falsch beantwortet. Korrigieren Sie!");
define('FRA_TxAnders',"Falsch, die richtige Antwort zur Frage #N h�tte gelautet:");
define('FRA_TxAnsEnde',"die Frage #N jetzt [i]nicht[/i] beantworten, am Ende erneut vorlegen");
define('FRA_TxLernen',"Lernmodus: Die L�sung zur Frage #N lautet:");
define('FRA_TxLernOk',"Lernmodus: Sie haben alle #Z Fragen und Antworten gesehen.");
define('FRA_TxZeigeLoesung','L�sung zur Frage-Nr. #N');
define('FRA_TxNichtGefunden',"Die Frage Nummer #N wurde nicht gefunden.");
define('FRA_TxKeineNummer',"keine Fragenummer gegeben!");
define('FRA_TxZeitLimit',"Die Bearbeitungszeit ist abgelaufen. Hier Ihr Ergebnis.");
define('FRA_TxBewertungHier',"Sie haben alle #Z Fragen abgearbeitet. Hier Ihr Ergebnis.");
define('FRA_TxAllesFertig',"Sie haben den gesamten Test mit allen #Z Fragen absolviert!");
define('FRA_TxFertigText','Das war es dann.\n \n \n [b]Tsch��[/b]');
define('FRA_TxDrucken','Stellen Sie Ihre Druckliste zusammen!');
define('FRA_TxDruckGanzeListe','Gesamt-Fragenliste');
define('FRA_TxDruckFilterListe','Auszug aus der Fragenliste');
define('FRA_TxDruckFilter','Auswahl der zu druckenden Fragen anhand folgender Filterbedingungen:');
define('FRA_TxDruckSpalten','In der Druckliste sollen folgende Spalten erscheinen:');
define('FRA_TxDruckNrOriginal','Original-Nummer');
define('FRA_TxDruckNrCronolog','chronologisch');
define('FRA_TxZeigeRichtig','korrekt beantwortet');
define('FRA_TxZeigeUnnuetz','unzutreffend gew�hlt');
define('FRA_TxZeigeFehlt','h�tte gew�hlt sein m�ssen');
define('FRA_TxZeigeLeer','nicht zutreffend');
define('FRA_TxZeigeWertung','#P von #G Punkten');
define('FRA_TxRestZeit','Restzeit');
define('FRA_TxNeuStart',"Test erneut starten");

//Teilnehmerregistrierung
define('FRA_TxLoginErfassen',"Registrierung nur f�r diesen Testdurchlauf.");
define('FRA_TxTeilnehmerSperre','Der Zugang f�r Teilnehmer ist momentan gesperrt.');
define('FRA_TxVorVorErfassen',"Vor Beginn des Testes m�ssen Sie sich erst registrieren.");
define('FRA_TxNachVorErfassen',"Ihre Daten wurden erfasst. Beginnen Sie nun mit dem Beantworten der Fragen.");
define('FRA_TxVorNachErfassen',"Sie haben alle # Fragen abgearbeitet. Tragen Sie Ihre Daten ein.");
define('FRA_TxRegistNicht','Sie haben weniger als das Limit erreicht.
 Der Versuch wird nicht gewertet.');

// Benutzerverwaltung
define('FRA_TxAnmelden','Anmelden');
define('FRA_TxSenden','Senden');
define('FRA_TxBenutzer','Benutzer');
define('FRA_TxBenutzername','Benutzername');
define('FRA_TxGewuenscht','gew�nschter');
define('FRA_TxMailAdresse','e-Mail-Adresse');
define('FRA_TxPasswort','Passwort');
define('FRA_TxNutzerNr','Benutzernummer');
define('FRA_TxNutzerFrist','g�ltig bis');
define('FRA_TxNutzerAblauf','abgelaufen');
define('FRA_TxNutzerRegel','(4...25 Zeichen)');
define('FRA_TxPassRegel','(4...16 Zeichen)');
define('FRA_TxLoginLogin','Zugang f�r angemeldete Benutzer');
define('FRA_TxLoginNeu',"Benutzerzugang jetzt beantragen");
define('FRA_TxLoginVergessen',"vergessenes Passwort zusenden");
define('FRA_TxNutzerLogin',"Vor Beginn des Testes m�ssen Sie sich registrieren oder anmelden.");
define('FRA_TxNutzerSperre','Der Zugang f�r Benutzer ist momentan gesperrt');
define('FRA_TxLoginNicht','Sie haben weniger als das Limit erreicht.
 Der Versuch wird nicht eingetragen.');
define('FRA_TxNutzerNamePass',"Bitte Benutzernamen und Passwort angeben!");
define('FRA_TxNutzerNameMail',"Bitte Benutzernamen oder e-Mail-Adresse angeben!");
define('FRA_TxEingabeFehl',"Erg�nzen Sie bei den rot markierten Feldern!");
define('FRA_TxNutzerFalsch',"Ein Benutzer mit diesen Daten ist nicht verzeichnet!");
define('FRA_TxNutzerPruefe',"Pr�fen und best�tigen Sie bitte Ihre Benutzerdaten!");
define('FRA_TxNutzerAendere','�ndern Sie jetzt die Benutzerdaten ab!'); //Adm
define('FRA_TxNutzerVergeben',"Dieser Benutzername ist bereits vergeben!");
define('FRA_TxNutzerNeu',"Die Benutzerdaten wurden eingetragen und der Webmaster informiert!");
define('FRA_TxNutzerUnveraendert',"Die Benutzerdaten bleiben unver�ndert!");
define('FRA_TxNutzerGeaendert',"Die ge�nderten Benutzerdaten wurden eingetragen!");
define('FRA_TxNutzerOK',"Sie wurden angemeldet. Beginnen Sie nun mit dem Beantworten der Fragen.");
define('FRA_TxNutzerSend',"Die Zugangsdaten wurden soeben versandt!");
define('FRA_TxSendeFehl','Die Nachricht konnte soeben nicht versandt werden!');
define('FRA_TxNutzerDatBtr',"Zugangsdaten bei #");
define('FRA_TxNutzerDaten','Sehr geehrte Damen und Herren,\n \n Sie haben soeben Ihre Zugangsdaten zum Testfragen-Script auf #A angefordert. Diese lauten:\n \n Benutzernummer: #N\n Benutzer: #B\n Passwort: #P');
define('FRA_TxNutzerNeuBtr',"Ihre Anmeldung bei #");
define('FRA_TxNutzerNeuTxt','Ihre Anmeldung bei #A wurde registriert. Bitte best�tigen Sie die Anmeldung �ber den Link\n \n #L\n \n Hier Ihre Anmeldedaten:\n #D');
define('FRA_TxNutzNeuAdmBtr',"neuer Testfragen-Script-Benutzer Nr. #");
define('FRA_TxNutzNeuAdmTxt','Ein neuer Testfragen-Script-Benutzer Nr. #N hat sich wie folgt angemeldet:\n \n #D');
define('FRA_TxNutzerAktivBtr',"Zugang aktiviert bei #");
define('FRA_TxNutzerAktivTxt','Sehr geehrte Damen und Herren,\n \n Ihr Benutzerzugang bei #A wurde soeben vom Webmaster freigeschaltet.\n \n Hier Ihre Anmeldedaten: \n \n #D');
define('FRA_TxPassiv',"Der Benutzerzugang ist nicht freigeschaltet.");
define('FRA_TxAktivieren',"Benutzerzugang jetzt aktivieren?");
define('FRA_TxAktiviert',"Ihr Benutzerzugang wurde aktiviert!");
define('FRA_TxAktivFehl',"Der Freischaltcode ist ung�ltig!");
define('FRA_TxDSE1',"Ich habe die [L]Datenschutzerkl�rung[/L] gelesen und stimme ihr zu.");
define('FRA_TxDSE2',"Ich bin mit der Verarbeitung und Speicherung meiner pers�nlichen Daten im Rahmen der Datenschutzerkl�rung einverstanden.");
define('FRA_TxSessionZeit','Die Sitzungszeit ist abgelaufen - bitte erneut anmelden!');
define('FRA_TxSessionUngueltig','Die Sitzung ist ung�ltig - bitte anmelden!');

//Benutzerzentrum
define('FRA_TxBenutzerzentrum','Benutzerzentrum');
define('FRA_TxTeilnehmerzentrum','Testauswahl');
define('FRA_TxAbmelden','Sitzung beenden');
define('FRA_TxTestNr','Test-#:');
define('FRA_TxTestName','Testname');
define('FRA_TxStandardTest','Standardtest');
define('FRA_TxSpontanFolge','Spontanfolge');
define('FRA_TxErgebnisListe','Ergebnisliste');
define('FRA_TxNutzerStatName','Bestenliste');
define('FRA_TxNutzerAendern','Benutzerdaten �ndern');
define('FRA_TxErgebnisLoesung','L�sungsseite anzeigen');
define('FRA_TxErgebnisDrucken','L�sungsseiten drucken');
define('FRA_TxErgebnisDetails','Details anzeigen');
define('FRA_TxStatistik',"Die bisher besten Resultate lauten:");
define('FRA_TxAktivCodeNoetig','Geben Sie den korrekten Aktiv-Code an!');
define('FRA_TxKeinTlnNam','Gast');
define('FRA_TxKeinNtzNam','unbekannt');

// BB-Formatleiste
define('FRA_TxBB_X','Schreiben Sie hier Ihren Text. Markieren Sie dann gew�nschte Textpassagen und formatieren sie mit dem passenden Schalter.');
define('FRA_TxBB_B','fetterText: [b]Text[/b]');
define('FRA_TxBB_I','kursiver Text: [i]Text[/i]');
define('FRA_TxBB_U','unterstrichener Text: [u]Text[/u]');
define('FRA_TxBB_H','hochgestellter Text: [sup]Text[/sup]');
define('FRA_TxBB_D','tiefgestellter Text: [sub]Text[/sub]');
define('FRA_TxBB_C','zentrierter Text: [center]Text[/center]');
define('FRA_TxBB_R','rechsb�ndiger Text: [right]Text[/right');
define('FRA_TxBB_E','Aufz�hlung: [list]Text[/list]');
define('FRA_TxBB_N','Numerierung: [list=o]Text[/list]');
define('FRA_TxBB_L','Link einf�gen: [url]www.domain.de[/url] oder [url]www.domain.de Linktext[/url]');
define('FRA_TxBB_P','Bild: [img]pfad/datei.jpg[/img] oder [img]http://www.domain.de/pfad/datei.gif[/img]');
define('FRA_TxBB_V','Video: [video]pfad/datei.mp4[/video] oder [video Breite H�he]https://www.domain.de/pfad/datei.ogg[/video]');
define('FRA_TxBB_Y','Youtube: [youtube Breite H�he]https://www.youtube.com/embed/ID-Code[/youtube]');
define('FRA_TxBB_A','Audio: [audio]pfad/datei.mp3[/audio] oder [audio]https://www.domain.de/pfad/datei.mp3[/audio]');
define('FRA_TxBB_O','Schriftfarbe: [color=blue]Text[/color]');
define('FRA_TxBB_S','Schriftgr��e: [size=+2]grosser Text[/size]');

// System-Fehler
define('FRA_TxSetupFehlt','Bitte zuerst das Setup/Update in der Administration ausf�hren!');
define('FRA_TxDateiRechte','Unzureichende Schreibrechte beim Speichern von #! (Setup-Fehler)');
define('FRA_TxSqlVrbdg','Entschuldigung - momentan MySQL-Verbindungsfehler');
define('FRA_TxSqlDaBnk','Entschuldigung - momentan MySQL-Datenbankauswahlfehler');
define('FRA_TxSqlFrage','Entschuldigung - momentan MySQL-Abfragefehler');
define('FRA_TxSqlEinfg','Entschuldigung - momentan MySQL-Einf�gefehler');
define('FRA_TxSqlAendr','Entschuldigung - momentan MySQL-�nderungsfehler');

// Ende
?>
