<?php
// Setup
define('MP_Version','3.5_2023-05-28');
define('MP_WarnMeldungen',false);
define('MP_Www','');
define('MP_Pfad','./');
define('MP_DocRoot','');
define('MP_RelPfad','');
define('MP_Daten','daten/');
define('MP_Bilder','bilder/');
define('MP_BldTrennen',false);
define('MP_Inserate','inserate.txt');
define('MP_Struktur','struktur.txt');
define('MP_Nutzer','nutzer00.txt');
define('MP_MailAdr','mailadr00.txt');
define('MP_Benachr','benachr00.txt');
define('MP_SQL',false);
define('MP_SqlHost','localhost');
define('MP_SqlDaBa','Ihre_Datenbank');
define('MP_SqlUser','test');
define('MP_SqlPass','test');
define('MP_SqlTabI','mp_%inserate');
define('MP_SqlTabS','mp_struktur');
define('MP_SqlTabN','mp_nutzer');
define('MP_SqlTabM','mp_mailadr');
define('MP_SqlTabB','mp_benachr');
define('MP_Schluessel','00');

// Administration
define('AM_Breite',1000);
define('AM_Hoehe',850);
define('AM_MitLogin',false);
define('AM_Admin','admin');
define('AM_Passwort','');
define('AM_AuthLogin',false);
define('AM_Author','inserteverwalter');
define('AM_AuthPass','');
define('AM_AuthCronJob',false);
define('AM_SessionsAgent',true);
define('AM_SessionsIPAddr',true);
define('AM_SqlZs',""); //'', 'latin1', 'utf8'
define('AM_Rueckwaerts',false);
define('AM_ArchivRueckwaerts',false);
define('AM_ZeigeAltes',false);
define('AM_ZeigeOnline',true);
define('AM_ZeigeOffline',false);
define('AM_ZeigeVormerk',false);
define('AM_BildVorschau',true);
define('AM_DateiSymbol',false);
define('AM_LinkSymbol',false);
define('AM_SymbSymbol',true);
define('AM_ListenLaenge',10);
define('AM_DetailInfo',-1);
define('AM_VormerkAlle',true);
define('AM_NutzerLaenge',15);
define('AM_NutzerFelder',7);
define('AM_NutzerBetreff',"Ihr Inserateeintrag hier");
define('AM_NutzerKontakt','Sehr geehrte Damen und Herren,\n    \n Sie haben im Marktplatz.....');
define('AM_Hilfe','https://www.server-scripts.de/marktplatz/');

//Allgemein
define('MP_Echo',true);
define('MP_Schablone',true);
define('MP_CanoLink',false);
define('MP_CanoPopup',false);
define('MP_Sef',false);
define('MP_Segmente',"#");
define('MP_Anordnung','0');
define('MP_HalteAltesNochTage',300);
define('MP_BearbAltesNochTage',14);
define('MP_ErrorPage',false);
define('MP_SqlCharSet','');
define('MP_Zeichensatz',2); //0:Standard 1:HTML-&-maskiert 2:UTF-8
define('MP_ZeichnsNorm',0);
define('MP_ZeichnsPopf',0);
define('MP_ZeichnsExtLink',0); //0:URL-ASCII, 1:URL-UTF-8, 2:UTF-8, 3:ASCII
define('MP_TimeZoneSet','Europe/Berlin');
define('MP_Datumsformat',1); //0:JJJJ-MM-TT 1:TT.MM.JJ 2:MM/TT/JJ 3:TT/MM/JJ 4:TT-MM-JJ
define('MP_Jahrhundert',true);
define('MP_Dezimalzeichen',",");
define('MP_Dezimalstellen','2');
define('MP_Tausendzeichen','');
define('MP_ZahlLeer',false);
define('MP_Waehrung',"&#8364;");
define('MP_PreisLeer',false);
define('MP_PLZLaenge',5);
define('MP_NummerMitSeg',true);
define('MP_NummerStellen','03');
define('MP_PopupBreit',700);
define('MP_PopupHoch',650);
define('MP_PopupX',10);
define('MP_PopupY',5);
define('MP_DruckPopup',true);
define('MP_DSELink','datenschutz.html');
define('MP_DSETarget','_blank');
define('MP_DSEPopUp',false);
define('MP_DSEPopupW',950);
define('MP_DSEPopupH',600);
define('MP_DSEPopupX',5);
define('MP_DSEPopupY',5);
define('MP_Captcha',true);
define('CAPTCHA_SALT','N22440');
define('MP_CaptchaTyp','G');
define('MP_CaptchaGrafisch',true);
define('MP_CaptchaNumerisch',false);
define('MP_CaptchaTextlich',false);
define('MP_CaptchaPfad','captcha/');
define('MP_CaptchaSpeicher','captcha.csv');
define('MP_CaptchaHgFarb','#F3F3F3');
define('MP_CaptchaTxFarb','#880000');
define('MP_MailTo','webmaster@domain.com');
define('MP_MailFrom','Marktplatz-Script <webmaster@domain.de>');
define('MP_CronMail',false);
define('MP_Smtp',false);
define('MP_SmtpHost','localhost');
define('MP_SmtpPort',25);
if(!defined('SMTP_No_TLS')) define('SMTP_No_TLS',true);
define('MP_SmtpAuth',false);
define('MP_SmtpUser','');
define('MP_SmtpPass','');
define('MP_EnvelopeSender','');
define('MP_KeineAntwort','keineAntwort <noreply@domain.de>');

// Links ueber/unter dem Marktplatz
define('MP_LinkAnf',"&nbsp;[&nbsp;");
define('MP_LinkEnd',"&nbsp;]&nbsp;");
define('MP_LinkOIndx',"Überblick");
define('MP_LinkOList',"Liste");
define('MP_LinkODrck',"Druck");
define('MP_LinkOSuch',"Suche");
define('MP_LinkOEing',"Eintrag");
define('MP_LinkOAend',"Ändern");
define('MP_LinkOLogi',"Anmelden");
define('MP_LinkOLogx',"Abmelden");
define('MP_LinkUIndx',"Übersicht");
define('MP_LinkUList',"Liste");
define('MP_LinkUDrck',"Drucken");
define('MP_LinkUSuch',"Suchen");
define('MP_LinkUEing',"Inserieren");
define('MP_LinkUAend',"Ändern");
define('MP_LinkULogi',"Anmelden");
define('MP_LinkULogx',"Abmelden");
define('MP_LinkZ1',"");
define('MP_LinkZ2',"");
define('MP_LinkZ3',"");
define('MP_LinkZ4',"");
define('MP_LinkZ5',"");
define('MP_LinkZ6',"");
define('MP_LinkZ7',"");
define('MP_LnkOIndxN',false);
define('MP_LnkOListN',false);
define('MP_LnkODrckN',false);
define('MP_LnkOSuchN',false);
define('MP_LnkOEingN',false);
define('MP_LnkOAendN',false);
define('MP_LnkOLogiN',false);
define('MP_LnkUIndxN',false);
define('MP_LnkUListN',false);
define('MP_LnkUDrckN',false);
define('MP_LnkUSuchN',false);
define('MP_LnkUEingN',false);
define('MP_LnkUAendN',false);
define('MP_LnkULogiN',false);
define('MP_LnkZ1N',false);
define('MP_LnkZ2N',false);
define('MP_LnkZ3N',false);
define('MP_LnkZ4N',false);
define('MP_LnkZ5N',false);
define('MP_LnkZ6N',false);
define('MP_LnkZ7N',false);

//Startseite
define('MP_IndexInZeilen',true);
define('MP_IndexZeilen',3);
define('MP_IndexSpalten',2);
define('MP_IndexFuellen',false);
define('MP_IndexZelleW','190px');
define('MP_IndexZelleH','50px');
define('MP_IndexHorizontal','left');
define('MP_IndexVertikal','middle');
define('MP_SuchQFilter',0);
define('MP_SuchQLeer',false);
define('MP_IndexAktO',true);
define('MP_IndexAktU',true);
define('MP_IndexAktZ',true);
define('MP_IndexZaehler',true);
define('MP_IndexIcons',true);
define('MP_IndexIconLinks',true);
define('MP_IndexNormal',false);

//Inserateliste
define('MP_ListenLaenge',5);
define('MP_Rueckwaerts',false);
define('MP_ArchivRueckwaerts',false);
define('MP_SuchFilter',2);
define('MP_NaviOben',2);
define('MP_NaviUnten',1);
define('MP_NaviBild',true);
define('MP_DetailPopup',false);
define('MP_MailPopup',true);
define('MP_EigeneZeilen',false);
define('MP_SegTrnZeile',true);
define('MP_ListeVertikal','');
define('MP_NListeAnders',false);
define('MP_NVerstecktSehen',true);
define('MP_NutzerListFeld',6);
define('MP_NNutzerListFeld',6);
define('MP_ListenInfo',3);
define('MP_ListenInfTitel',"Info");
define('MP_GastLInfo',true);
define('MP_ListenBenachr',-1);
define('MP_ListenBenachTitel',"Nachricht");
define('MP_GastLBenachr',false);
define('MP_ListenAendern',-1);
define('MP_ListenAendTitel',"Ändern");
define('MP_GastLAendern',false);
define('MP_ListenKopieren',-1);
define('MP_ListenKopieTitel',"Kopieren");
define('MP_GastLKopieren',false);
define('MP_ListenAendKopieren',true);
define('MP_LinkSymbol',true);
define('MP_SymbolTyp','jpg');
define('MP_ErsatzBildKlein','');
define('MP_ListenMemoLaenge',0);
define('MP_DruckLMemoLaenge',0);
define('MP_DruckLMailOffen',false);
define('MP_DruckLMemo',false);
define('MP_DruckLFarbig',false);

//Inseratedetails
define('MP_DetailNaviOben',1);
define('MP_DetailNaviUnten',1);
define('MP_DetailNaviBild',true);
define('MP_NDetailAnders',false);
define('MP_NutzerDetailFeld',2);
define('MP_NNutzerDetailFeld',2);
define('MP_EigeneDetails',false);
define('MP_ZeigeLeeres',false);
define('MP_DetailInfo',3);
define('MP_GastDInfo',true);
define('MP_DetailBenachr',-1);
define('MP_GastDBenachr',true);
define('MP_DetailAendern',3);
define('MP_GastDAendern',true);
define('MP_DetailKopieren',3);
define('MP_GastDKopieren',true);
define('MP_DetailDrucken',3);
define('MP_GastDDrucken',true);
define('MP_DruckDFarbig',false);
define('MP_DruckDMailOffen',false);
define('MP_DetailLinkSymbol',false);
define('MP_DetailDateiSymbol',false);
define('MP_ErsatzBildGross','');
define('MP_DTitelQuelle',1);
define('MP_DTitelWL',3);
define('MP_DTitelZL',30);

//Eingabeformular
define('MP_Direkteintrag',false);
define('MP_Direktaendern',0);
define('MP_FormatCode',true);
define('MP_NEingabeLogin',false);
define('MP_NAendernFremde',false);
define('MP_NEingabeAnders',false);
define('MP_AendernMitLoeschen',true);
define('MP_AendernOnOff',true);
define('MP_BildMaxKByte',150);
define('MP_DateiMaxKByte',80);
define('MP_BildBreit',480);
define('MP_BildHoch',330);
define('MP_VorschauRahmen',false);
define('MP_VorschauBreit',90);
define('MP_VorschauHoch',80);
define('MP_ThumbBreit',90);
define('MP_ThumbHoch',64);
define('MP_BildResize',true);
define('MP_EintragszeitNeu',false);
define('MP_AendernCaptcha',false);
define('MP_AblaufdatumFest',false);
define('MP_EintragAdminInfo',true);
define('MP_EintragMail',true);
define('MP_AendernMail',true);
define('MP_FreischaltMail',true);
define('MP_EintragDSE1',false);
define('MP_EintragDSE2',false);
define('MP_MailListeAdr',"liste@domain.com");
define('MP_MailListeEintrag',false);
define('MP_MailListeAdmEint',true);
define('MP_MailListeFreischalt',true);
define('MP_MailListeAendern',false);
define('MP_MailListeAdmAend',true);
define('MP_MailListeNDetail',false);
define('MP_NutzerMailListeFeld',6);
define('MP_NutzerEMail',true);

// Suchformular
define('MP_SuchSpalten',2);
define('MP_SuchSortiert',false);
define('MP_SuchArchiv',true);

// Infoformular
define('MP_InfoNDetail',false);
define('MP_InfoMitMemo',false);
define('MP_NutzerInfoFeld',6);
define('MP_InfoAbsPflicht',true);
define('MP_InfoDSE1',false);
define('MP_InfoDSE2',false);
define('MP_InfoLink','');

// Kontaktformular
define('MP_KontaktNDetail',true);
define('MP_KontaktMitMemo',true);
define('MP_NutzerKontaktFeld',0);
define('MP_KontaktAbsPflicht',false);
define('MP_KontaktDSE1',false);
define('MP_KontaktDSE2',false);
define('MP_KontaktLink','');

// Google-Maps
define('MP_GMapSource','O'); // O: OSM oder G: GoogleMap
define('MP_GMapV3',true);
define('MP_GMapURL','http://maps.google.com/maps/api/js?sensor=false&language=de');
define('MP_GMapCode','');
define('MP_GMapTypeControl',true);
define('MP_SMapCode','');
define('MP_SMapTypeControl',false);
define('MP_SMap2Finger',true);
define('MP_GMapBreit',350);
define('MP_GMapHoch',250);
define('MP_GMapWarten',3);
define('MP_GMapBZentr',51.2206474304);
define('MP_GMapLZentr',10.4134723845);
define('MP_GMapZoom',6);

//Benutzerverwaltung
define('MP_NutzerFelder','Nummer;Session;aktiv;Benutzer;Passwort;E-Mail;Anrede;Vorname + Name;PLZ Ort;Strasse;Telefon, Mobil');
define('MP_NutzerPflicht','0;0;0;1;1;1;0;1;1;0;0');
define('MP_SessionZeit',45);
define('MP_NutzerNeuErlaubt',true);
define('MP_NutzerNeuAdmMail',true);
define('MP_NutzerNeuMail',true);
define('MP_NutzerAktivMail',true);
define('MP_FreischaltAdmin',false);
define('MP_FreischaltWin','Freischalt');
define('MP_ErinnOkMail',false);
define('MP_BenachrOkMail',false);
define('MP_FreischaltNeuMail',true);
define('MP_NutzerLoeschen',0);
define('MP_NutzerDSE1',false);
define('MP_NutzerDSE2',false);
define('MP_LoginCaptcha',true);
define('MP_MaxSessionZeit',1);
define('MP_GuthabenNeu',1);
define('MP_WarnFristNeu',3);
define('MP_AgbLink','');
define('MP_AgfLink','');
define('MP_AgbPopup',true);
define('MP_AgbBreit',750);
define('MP_AgbHoch',650);
define('MP_AgbZiel','');
define('MP_BenachrNDetail',false);
define('MP_BenachrMitMemo',false);
define('MP_NutzerBenachrFeld',2);
define('MP_BenachrLink','');
define('MP_PasswortSenden',true);

//neue Inserate
define('MP_NeueAnzahl',5);
define('MP_NeueTage',8);
define('MP_NeueNachEintrag',true);
define('MP_NeueNachEZeit',2);
define('MP_NeueRueckwaerts',false);
define('MP_NeueKopf',true);
define('MP_NeueSegTrnZ',true);
define('MP_NeueAbstand',5);
define('MP_NeueEigeneZeilen',false);
define('MP_NeueFelder',"");
define('MP_NeueCssStyle',false);
define('MP_NeueLink',"");
define('MP_NeueTarget',"");
define('MP_NeuePopup',false);

/* Sprachfloskeln */
// Kürzel
define('MP_TxSymbJhr','JJ');
define('MP_TxSymbMon','MM');
define('MP_TxSymbTag','TT');
define('MP_TxSymbUhr','hh:mm');
define('MP_TxJa','Ja');
define('MP_TxNein','Nein');
define('MP_TxUnd','und');
define('MP_TxOder','oder');
define('MP_TxAm','am');
define('MP_TxIm','im');
define('MP_TxBis','bis');
define('MP_TxWie','wie');
define('MP_TxIst','ist');
define('MP_TxBzwAb','bzw. ab');
define('MP_TxAberNicht','aber nicht wie');
define('MP_TxNicht','nicht');
define('MP_TxMaximal','max.');

//Allgemein
define('MP_TxMarkt','Marktplatz');
define('MP_TxSegment','Segment');
define('MP_TxInserat','Inserat');
define('MP_TxInserate','Inserate');
define('MP_TxAMetaKey',"Kleinanzeigen, Inserate");
define('MP_TxAMetaDes',"Kleinanzeigenmarkt");
define('MP_TxAendern','ändern');
define('MP_TxKopieren','kopieren');
define('MP_TxLoeschen','löschen');
define('MP_TxDrucken','drucken');
define('MP_TxFld0Nam','Nummer');
define('MP_TxFld1Nam','Ablauf');
define('MP_TxIndexSeite',"Marktplatz-Rubrikenübersicht");
define('MP_ZusatzHtm','Schablonenseite mpZusatz#.htm fehlt!');

//Inserateliste
define('MP_TxListGsmt',"#S: #AGesamtliste");
define('MP_TxListSuch',"#S: #ASuchergebnis für #F");
define('MP_TxListQGsmt',"Gesamtliste");
define('MP_TxListQSuch',"Suchergebnis für #F");
define('MP_TxQuerSuche',"Schnellsuche");
define('MP_TxLMetaKey',"#S, Kleinanzeigen");
define('MP_TxLMetaDes',"Kleinanzeigen zum Thema #S");
define('MP_TxLMetaTit',":: Rubrik #S");
define('MP_TxSuchMeld','Suchen Sie im Segment #S!');
define('MP_TxSortieren','sortieren');
define('MP_TxAufsteigend','aufsteigend ');
define('MP_TxAbsteigend','absteigend ');
define('MP_TxDatei','Datei');
define('MP_TxDiese','diese');
define('MP_TxNaechste','nächste');
define('MP_TxVorige','vorige');
define('MP_TxSeite','Seite');
define('MP_TxNummer','Nummer');
define('MP_TxAnfang','Anfang');
define('MP_TxEnde','Ende');
define('MP_TxArchiv','Archiv');
define('MP_TxSuchen','Suchen');
define('MP_TxRueckwaerts','rückwärts');
define('MP_TxSondersuche','Sondersuche');
define('MP_TxKontakt','Kontakt');
define('MP_TxSendInfo','Information versenden');

//Inseratedetails
define('MP_TxDetails',"#S: Details zum Inserat #N");
define('MP_TxDMetaKey',"#S, Inserat");
define('MP_TxDMetaDes',"Inserat zum Thema #S");
define('MP_TxDMetaTit',":: Inserat zu #S");
define('MP_TxDetail','Inseratedetails');
define('MP_TxUhr','Uhr');
define('MP_TxNummerUngueltig','Datensatznummer ungültig!');
define('MP_TxInfoSenden',"Info senden");
define('MP_TxBenachServ','Benachrichtigung');
define('MP_TxBenachrService',"Benachrichtigung anfordern");
define('MP_TxGMapOrt','Veranstaltungsort');
define('MP_TxGMap1Warten',"Karte wird geladen.....");
define('MP_TxGMap2Warten',"anderenfalls hier klicken");
define('MP_TxKeinDetail','HTML-Schablone detail.htm fehlt!');
define('MP_TxKontaktSenden',"Kontakt aufnehmen");
define('MP_TxAutorGast','Gast');
define('MP_TxZumAnfang','rückwärts blättern');
define('MP_TxZumEnde','vorwärts blättern');
define('MP_TxAutor0000','Administrator');
define('MP_TxAutorUnbekannt','unbekannt');

//Eingabeformular
define('MP_TxEingabe','Eintragen');
define('MP_TxInseratNeu','neues Inserat');
define('MP_TxInseratAendern','Inserat ändern');
define('MP_TxInseratFremd','fremdes');
define('MP_TxInseratEigen','eigenes');
define('MP_TxPflicht','Pflichtfeld');
define('MP_TxFormat','Format');
define('MP_TxStellen','Stellen');
define('MP_TxStatus','Status');
define('MP_TxOnline','online/sichtbar');
define('MP_TxOffline','offline/unsichtbar');
define('MP_TxVormerk','wartet auf Freigabe');
define('MP_TxKoordinaten','Koordinaten bearbeiten');

define('MP_TxCaptchaFeld','Sicherheitscode');
define('MP_TxCaptchaNeu','neues #Captcha anfordern');
define('MP_TxZahlenCaptcha','Zahlen-');
define('MP_TxTextCaptcha','Text-');
define('MP_TxGrafikCaptcha','Grafik-');
define('MP_TxCaptchaHilfe','Bitte den Buchstaben und die 4 Ziffern übertragen');
define('MP_TxCaptchaFehl','Bitte geben Sie den Sicherheitscode korrekt ein!');
define('MP_TxEingabeMeld',"Tragen Sie jetzt Ihr neues Inserat ein!");
define('MP_TxEingabeErfo','Das Inserat wurde eingetragen und veröffentlicht!');
define('MP_TxEingabeOffl',"Das Inserat wurde eingetragen aber nicht veröffentlicht!");
define('MP_TxVormerkErfo','Das Inserat wurde vorgemerkt und der Webmaster informiert!');
define('MP_TxEingabeFehl','Ergänzen Sie bei den rot markierten Feldern!');
define('MP_TxExIntervall','Das Datum liegt ausserhalb des zulässigen Bereichs!');
define('MP_TxBildTyp','Bilder mit der Endung # sind nicht erlaubt!');
define('MP_TxBildGroesse','Bilder über # KByte werden nicht verarbeitet!');
define('MP_TxDateiTyp','Dateien vom Typ # sind nicht erlaubt!');
define('MP_TxDateiGroesse','Dateien über # KByte werden nicht gespeichert!');
define('MP_TxBildOeffnen','Das Bild # konnte nicht geöffnet werden!');
define('MP_TxEintragAdminBtr',"neuer Inserateeintrag #N in #S");
define('MP_TxAendernAdminBtr',"geaenderter Inserateeintrag #N in #S");
define('MP_TxEintragAdminTxt','Im Marktplatz wurde folgender Eintrag Nr. #N im Segment #S vorgenommen:\n \n #D');
define('MP_TxEintragBtr',"Re: Ihr Inserateeintrag");
define('MP_TxAendernBtr',"Re: Ihr geaenderter Inserateeintrag");
define('MP_TxEintragTxt','Ihr Eintrag Nr. #N im Segment #S im Marktplatz bei #A wurde mit folgenden Daten entgegengenommen:\n \n #D\n \n Vielen Dank!');
define('MP_TxFreischaltBtr',"Re: Inserateeintrag freigeschaltet");
define('MP_TxFreischaltTxt','Ihr Eintrag Nr. #N im Segment #S im Marktplatz bei #A wurde mit folgenden Daten freigeschaltet:\n \n #D');
define('MP_TxMailListeBtr',"neuer Inserateeintrag bei #A");
define('MP_TxMailLstBtrAend',"geaenderter Inserateeintrag bei #A");
define('MP_TxMailListeTxt','Im Marktplatz bei #A wurde folgendes Inserat im Segment #S veröffentlicht:\n \n #D');
define('MP_TxKopiereMeld','Kopieren Sie dieses Inserat als neues Inserat!');
define('MP_TxKeinKopieFeld','Es gibt keine passenden Felder im Zielsegment!');
define('MP_TxKopiereErfo','Die Inseratekopie wurde eingetragen und veröffentlicht!');

//Änderungsformular
define('MP_TxInserateNr','Inseratenummer');
define('MP_TxNummerFehlt','Bitte geben Sie die laufende Inseratenummer an!');
define('MP_TxNummerUnbek','Datensatz nicht gefunden! Bitte geben Sie eine gültige Nummer an!');
define('MP_TxNummerPassw','Bitte geben Sie das korrekte Passwort zum Inserat an!');
define('MP_TxNummerFremd','Dieses Inserat gehört nicht Ihnen! Bitte wählen Sie eine gültiges Inserat!');
define('MP_TxAendereZuAlt','Dieses Inserat kann nicht mehr geändert werden!');
define('MP_TxAendereMeld','Ändern Sie jetzt dieses Inserat ab!');
define('MP_TxKeineAenderung','Die Daten bleiben unverändert.');
define('MP_TxAendereErfo','Die geänderten Inseratedatendaten wurden eingetragen!');
define('MP_TxAendereVmk','Die Änderungen wurden vorgemerkt und der Webmaster informiert!');
define('MP_TxNummerHilfe','Die Inseratenummer erfahren Sie (sofern sonst nirgends erkennbar) aus der Adresszeile Ihres Browsers nach Aufruf der Detailansicht zum Inserat.');
define('MP_TxLoeschFrage','Wollen Sie das markierte Inserat wirklich löschen?');
define('MP_TxLoeschErfol','Das markierte Inserat wurde gelöscht!');
define('MP_TxLoescheFrag','Wollen Sie das markierte Inserat wirklich löschen?');
define('MP_TxLoescheErfo','Die markierten Inserate wurden gelöscht!');

// Infoformular und Kontaktformular
define('MP_TxSenden','Senden');
define('MP_TxEmpfaenger','Empfänger');
define('MP_TxAbsender','Absender');
define('MP_TxInfoAbsender',"E-Mail-Absender");
define('MP_TxKontaktAbsender',"");
define('MP_TxBetreff','Betreff');
define('MP_TxMitteilung','Mitteilung');
define('MP_TxInfoLink','der Link lautet');
define('MP_TxInfoMeld','Informieren Sie einen Bekannten über dieses Inserat!');
define('MP_TxMailMeld','Treten Sie mit dem Verfasser des Inserates in Kontakt!');
define('MP_TxSendeErfo','Die Information wurde soeben versandt!');
define('MP_TxSendeFehl','Die Nachricht konnte soeben nicht versandt werden!');
define('MP_TxMailAn',"Verfasser des Inserates");
define('MP_TxInfoBtr',"interessantes Inserat");
define('MP_TxMailBtr',"Re: Ihr Inserateeintrag");
define('MP_TxInfoTxt','Hallo,\n \n unter der Adresse #A/markt/ habe ich im Segment #S ein interessantes Inserat gefunden. Unten der Link und ein Auszug.\n \n Mit freundlichen Grüßen');
define('MP_TxMailTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter der Adresse #A/markt ein Inserat im Segment #S veröffentlicht. Zu diesem Inserat interessiert mich ...\n \n Mit freundlichen Grüßen');

//Erinnerungsformular und Benachrichtigungsformular
define('MP_TxBenachrMeld','Fordern Sie eine Benachrichtigung bei Inserateänderung an.');
define('MP_TxBenachrErfo','Ihr Benachrichtigungswunsch wurde vorgemerkt.');
define('MP_TxBenachrOkBtr',"Re: Benachrichtigung bei #A vorgemerkt");
define('MP_TxBenachrOkTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A  im Segment #S eine Benachrichtigung angefordert. Diese wird bei Veränderungen zu folgendem Inserat erfolgen:\n \n #D\n \n Mit freundlichen Grüßen');
define('MP_TxBenachrUnbekannt','#N ist für diesen Dienst noch nicht freigeschaltet.\n Sie können jetzt die Freischaltung durch Senden des Formulars anfordern.');
define('MP_TxBenachrUnmoegl','#N ist für diesen Dienst nicht vorgesehen.\n Wenden Sie sich an den Webmaster.');
define('MP_TxBenachrUnbkBtr',"Re: Ihr Benachrichtigungswunsch bei #A");
define('MP_TxBenachrUnbkTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A im Segment #S eine Benachrichtigung angefordert.\n \n Ihre E-Mail-Adresse ist für diesen Dienst noch nicht freigeschaltet. Sie können diese Freischaltung erreichen, indem Sie jetzt den Link\n \n #L\n \n aufrufen.\n \n Mit freundlichen Grüßen');
define('MP_TxBenachrSendBtr',"Inserateänderung bei #A");
define('MP_TxBenachrSendTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A im Segment #S eine Benachrichtigung erbeten, falls sich am nachfolgenden Inserat etwas geändert hat.\n \n #D\n \n Mit freundlichen Grüßen');
define('MP_TxEMailFrei','E-Mail-Adresse freischalten');
define('MP_TxEMailErfo','Ihre E-Mail-Adresse wurde freigegeben.\n Sie können jetzt Erinnerungen oder Benachrichtigungen anfordern.');

//Benutzerverwaltung
define('MP_TxAnmelden','Anmelden');
define('MP_TxBenutzer','Benutzer');
define('MP_TxNutzerNr','Benutzernummer');
define('MP_TxBenutzerDat','Benutzerdaten');
define('MP_TxBenutzername','Benutzername');
define('MP_TxGewuenscht','gewünschter');
define('MP_TxAgbFeld',"");
define('MP_TxAgbText',"Ich akzeptiere die [AGB].");
define('MP_TxAgfFeld',"");
define('MP_TxAgfText',"Ich akzeptiere die [AGB].");
define('MP_TxAktiv','aktiviert');
define('MP_TxMailAdresse','E-Mail-Adresse');
define('MP_TxPasswort','Passwort');
define('MP_TxNutzerRegel','(4...25 Zeichen)');
define('MP_TxPassRegel','(4...16 Zeichen)');
define('MP_TxPassHilfe','zum Inserat gehörig');
define('MP_TxGuthaben','Guthaben');
define('MP_TxGuthaben0',"Ihr Guthaben ist aufgebraucht!");
define('MP_TxWarnen','Warnfrist');
define('MP_TxWarnTage','Tage vor Inserateablauf');
define('MP_TxWarnenBtr',"Inserateablauf bei #A");
define('MP_TxWarnenTxt','Ihr Inserat bei #A im Segment #S läuft demnächst ab und wird dann nicht länger angezeigt:\n \n #D');
define('MP_TxLoginLogin','Zugang für registrierte Benutzer');
define('MP_TxLoginNeu','Benutzerzugang jetzt beantragen');
define('MP_TxLoginVergessen','vergessenes Passwort zusenden');
define('MP_TxNutzerLogin',"Melden Sie sich für die Marktplatzbenutzung an!");
define('MP_TxNutzerNamePass',"Bitte Benutzernamen und Passwort angeben!");
define('MP_TxNutzerNameMail',"Bitte Benutzernamen oder E-Mail-Adresse angeben!");
define('MP_TxNutzerFalsch',"Ein Benutzer mit diesen Daten ist nicht verzeichnet!");
define('MP_TxNutzerPruefe',"Prüfen und bestätigen Sie bitte Ihre Benutzerdaten!");
define('MP_TxNutzerVergeben',"Dieser Benutzername ist bereits vergeben!");
define('MP_TxNutzerNeu',"Die Benutzerdaten wurden eingetragen und der Webmaster informiert!");
define('MP_TxNutzerGeaendert',"Die geänderten Benutzerdaten wurden eingetragen!");
define('MP_TxNutzerOK',"Sie sind nun angemeldet und können die gewünschte Aktion ausführen.");
define('MP_TxNutzerLogout',"Sie wurden erfolgreich abgemeldet!");
define('MP_TxNutzerSend',"Die Zugangsdaten wurden soeben versandt!");
define('MP_TxNutzerDatBtr',"Ihre Zugangsdaten");
define('MP_TxNutzerDaten','Sehr geehrte Damen und Herren,\n \n Sie haben soeben Ihre Zugangsdaten zum Marktplatz auf #A angefordert. Diese lauten:\n \n lfd. Nummer: #N\n Benutzer: #B\n Passwort: #P');
define('MP_TxNutzerNeuBtr',"Ihre Anmeldung");
define('MP_TxNutzerNeuTxt','Ihre Anmeldung bei #A wurde registriert. Bitte bestätigen Sie die Anmeldung über den Link\n \n #L\n \n Hier Ihre Anmeldedaten:\n #D');
define('MP_TxNutzNeuAdmBtr',"neuer Marktplatz-Benutzer Nr. #");
define('MP_TxNutzNeuAdmTxt','Ein neuer Marktplatz-Benutzer Nr. #N hat sich wie folgt angemeldet:\n \n #D');
define('MP_TxNutzerAktivBtr',"Benutzerzugang aktiviert");
define('MP_TxNutzerAktivTxt','Sehr geehrte Damen und Herren,\n \n Ihr Benutzerzugang bei #A wurde soeben vom Webmaster freigeschaltet.\n \n Hier Ihre Anmeldedaten: \n \n #D');
define('MP_TxNutzerLschMeld',"Der Administrator wurde über Ihren Löschwunsch informiert.");
define('MP_TxNutzerLschBtrA',"Nutzerzugang Nr. #N löschen");
define('MP_TxNutzerLschTxtA','Der Benutzer Nummer #N mit dem Benutzernamen #U möchte sein Konto löschen lassen.');
define('MP_TxNutzerLschBtrN',"Benutzerzugang bei #A gelöscht");
define('MP_TxNutzerLschTxtN','Hallo #U,\n \n Ihr Benutzerkonto mit der Benutzernummer #N auf der Webseite #A wurde soeben gelöscht.');
define('MP_TxAktivieren',"Benutzerzugang jetzt aktivieren?");
define('MP_TxAktiviert',"Ihr Benutzerzugang wurde aktiviert!");
define('MP_TxAktivFehl',"Der Freischaltcode ist ungültig!");
define('MP_TxDSE1',"Ich habe die [L]Datenschutzerklärung[/L] gelesen und stimme ihr zu.");
define('MP_TxDSE2',"Ich bin mit der Verarbeitung und Speicherung<br />meiner persönlichen Daten im Rahmen der<br />Datenschutzerklärung einverstanden.");
define('MP_TxSessionZeit','Die Sitzungszeit ist abgelaufen - bitte erneut anmelden!');
define('MP_TxSessionUngueltig','Die Sitzung ist ungültig - bitte anmelden!');

// BB-Formatleiste
define('MP_TxBB_X','Schreiben Sie hier Ihren Text. Markieren Sie dann gewünschte Textpassagen und formatieren sie mit dem passenden Schalter.');
define('MP_TxBB_B','fetterText: [b]Text[/b]');
define('MP_TxBB_I','kursiver Text: [i]Text[/i]');
define('MP_TxBB_U','unterstrichener Text: [u]Text[/u]');
define('MP_TxBB_C','zentrierter Text: [center]Text[/center]');
define('MP_TxBB_R','rechsbündiger Text: [right]Text[/right');
define('MP_TxBB_E','Aufzählung: [list]Text[/list]');
define('MP_TxBB_N','Numerierung: [list=o]Text[/list]');
define('MP_TxBB_L','Link einfügen: [url]www.domain.de[/url] oder [url]www.domain.de Linktext[/url]');
define('MP_TxBB_O','Schriftfarbe: [color=blue]Text[/color]');
define('MP_TxBB_S','Schriftgröße: [size=+2]grosser Text[/size]');

// System-Fehler
define('MP_TxSetupFehlt','Bitte zuerst das Setup/Update in der Administration ausführen!');
define('MP_TxDateiRechte','Unzureichende Schreibrechte beim Speichern von #! (Setup-Fehler)');
define('MP_TxKeinSegment',"Es ist momentan leider kein Marktsegment ausgewählt!");
define('MP_TxSqlVrbdg','Entschuldigung - momentan MySQL-Verbindungsfehler');
define('MP_TxSqlDaBnk','Entschuldigung - momentan MySQL-Datenbankauswahlfehler');
define('MP_TxSqlFrage','Entschuldigung - momentan MySQL-Abfragefehler');
define('MP_TxSqlEinfg','Entschuldigung - momentan MySQL-Einfügefehler');
define('MP_TxSqlAendr','Entschuldigung - momentan MySQL-Änderungsfehler');
?>