<?php
// Setup
define('KAL_Version','3.5_2023-06-03');
define('KAL_WarnMeldungen',false);
define('KAL_Www','');
define('KAL_Pfad','./');
define('KAL_DocRoot','');
define('KAL_RelPfad','');
define('KAL_Daten','daten/');
define('KAL_Bilder','bilder/');
define('KAL_Termine','termine.txt');
define('KAL_Vorgaben','vorgaben.txt');
define('KAL_Nutzer','nutzer00.txt');
define('KAL_Erinner','erinner00.txt');
define('KAL_Benachr','benachr00.txt');
define('KAL_MailAdr','mailadr00.txt');
define('KAL_AdminTexte','texteAdmin.txt');
define('KAL_SQL',false);
define('KAL_SqlHost','localhost');
define('KAL_SqlDaBa','Ihre_Datenbank');
define('KAL_SqlUser','sqluser');
define('KAL_SqlPass','??????');
define('KAL_SqlTabT','kal_termine');
define('KAL_SqlTabN','kal_nutzer');
define('KAL_SqlTabE','kal_erinner');
define('KAL_SqlTabB','kal_benachr');
define('KAL_SqlTabM','kal_mailadr');
define('KAL_SqlTabA','kal_texteadmin');
define('KAL_Schluessel','00');

// Administration
define('ADM_MitLogin',false);
define('ADM_Admin','admin');
define('ADM_Passwort','');
define('ADM_AuthLogin',false);
define('ADM_Author','terminverwalter');
define('ADM_AuthPass','');
define('ADM_AuthCronJob',false);
define('ADM_SessionsAgent',true);
define('ADM_SessionsIPAddr',true);
define('ADM_Hilfe','https://www.server-scripts.de/kalender/');
define('ADM_SqlZs','');
define('ADM_Breite',1000);
define('ADM_ListenIndex',1);
define('ADM_Rueckwaerts',false);
define('ADM_ArchivRueckwaerts',true);
define('ADM_ZeigeAltes',true);
define('ADM_ZeigeOnline',true);
define('ADM_ZeigeOffline',false);
define('ADM_ZeigeVormerk',false);
define('ADM_BildVorschau',false);
define('ADM_DateiSymbol',true);
define('ADM_LinkSymbol',false);
define('ADM_SymbSymbol',true);
define('ADM_ListenLaenge',25);
define('ADM_ListenMemoLaenge',60);
define('ADM_ListenZusagSp',-1);
define('ADM_ZusageTrmListe',true);
define('ADM_ZusageTrmEintrag',true);
define('ADM_TCalPicker',true);
define('ADM_DetailInfo',1);
define('ADM_NutzerLaenge',25);
define('ADM_NutzerFelder',9);
define('ADM_NutzerBetreff',"Ihr Termineintrag");
define('ADM_NutzerKontakt','Sehr geehrte Damen und Herren,\n    \n Sie haben im Kalender.....');

// Terminstruktur
$kal_FeldName=array("Nummer","Datum","Zeit","Ort","Veranstaltung","Ablauf");
$kal_FeldType=array('i','d','z','a','t','m');
$kal_ListenFeld= array(0,1,2,4,3,0);
$kal_SortierFeld=array(0,1,0,1,0,0);
$kal_LinkFeld=   array(0,1,0,0,1,0);
$kal_DetailFeld= array(1,1,1,1,1,1);
$kal_SuchFeld=   array(0,2,0,2,2,0);
$kal_EingabeFeld=array(0,1,1,1,1,1);
$kal_EingabeLang=array(0,0,0,0,0,0);
$kal_KopierFeld= array(0,1,1,1,1,1);
$kal_PflichtFeld=array(0,1,0,1,1,0);
$kal_SpaltenStil=array('','','','','font-weight:bold;','');
$kal_ZeilenStil= array('','','','','font-weight:bold;','');
$kal_NListenFeld=array(0,1,2,4,3,0);
$kal_NDetailFeld=array(1,1,1,1,1,1);
$kal_NKopierFeld=array(0,1,1,1,1,1);
$kal_NEingabeFeld=array(0,1,1,1,1,1);

//Allgemeines
define('KAL_Schablone',true);
define('KAL_HalteAltesNochTage',370);
define('KAL_ZeigeAltesNochTage',3);
define('KAL_BearbAltesNochTage',14);
define('KAL_TimeZoneSet','Europe/Berlin');
define('KAL_Datumsformat',1); //0:JJJJ-MM-TT 1:TT.MM.JJ 2:MM/TT/JJ 3:TT/MM/JJ 4:TT-MM-JJ
define('KAL_Jahrhundert',true);
define('KAL_MitWochentag',2);
define('KAL_EndeDatum',false);
define('KAL_Waehrung','EUR');
define('KAL_PreisLeer',true);
define('KAL_Dezimalstellen',2);
define('KAL_Dezimalzeichen',",");
define('KAL_Tausendzeichen',"");
define('KAL_ZahlLeer',false);
define('KAL_Captcha',true);
define('CAPTCHA_SALT','J97088');
define('KAL_CaptchaTyp','G');
define('KAL_CaptchaGrafisch',true);
define('KAL_CaptchaNumerisch',false);
define('KAL_CaptchaTextlich',false);
define('KAL_CaptchaPfad','captcha/');
define('KAL_CaptchaSpeicher','captcha.csv');
define('KAL_CaptchaHgFarb','#F3F3F3');
define('KAL_CaptchaTxFarb','#880000');
define('KAL_HtmlErlaubt',false);
define('KAL_SqlCharSet','');
define('KAL_Zeichensatz',2); //0:Standard 1:HTML-&-maskiert 2:UTF-8
define('KAL_LZeichenstz',0);
define('KAL_SZeichenstz',0);
define('KAL_LZsatzPopup',0);
define('KAL_SZsatzPopup',0);
define('KAL_ZSatzExtLink',2); //0:URL-ASCII, 1:URL-UTF-8, 2:UTF-8, 3:ASCII
define('KAL_Empfaenger','webmaster@domain.de');
define('KAL_EmpfTermin','');
define('KAL_EmpfNutzer','');
define('KAL_EmpfZusage','');
define('KAL_Sender','Kalender <webmaster@domain.de>');
define('KAL_Smtp',false);
define('KAL_SmtpHost','localhost');
define('KAL_SmtpPort',25);
if(!defined('SMTP_No_TLS')) define('SMTP_No_TLS',true);
define('KAL_SmtpAuth',false);
define('KAL_SmtpUser','');
define('KAL_SmtpPass','');
define('KAL_EnvelopeSender','');
define('KAL_KeineAntwort','keine-Antwort <noreply@domain.de>');
define('KAL_CronMail',false);
define('KAL_DruckPopup',true);
define('KAL_PopupBreit',700);
define('KAL_PopupHoch',800);
define('KAL_PopupX',5);
define('KAL_PopupY',5);
define('KAL_DSELink','datenschutz.html');
define('KAL_DSETarget','_blank');
define('KAL_DSEPopUp',false);
define('KAL_DSEPopupW',900);
define('KAL_DSEPopupH',600);
define('KAL_DSEPopupX',5);
define('KAL_DSEPopupY',5);

// Links über/unter dem Kalender
define('KAL_LinkAnf',"");
define('KAL_LinkEnd',"");
define('KAL_LinkLstLst',true);
define('KAL_LinkOList',"Terminliste");
define('KAL_LinkOMona',"");
define('KAL_LinkOWoch',"");
define('KAL_LinkODrck',"Drucken");
define('KAL_LinkOExpt',"");
define('KAL_LinkOSuch',"Suchen");
define('KAL_LinkOEing',"Eintragen");
define('KAL_LinkOAend',"Ändern");
define('KAL_LinkOLogi',"Anmelden");
define('KAL_LinkOLogx',"Abmelden");
define('KAL_LinkUList',"Terminliste");
define('KAL_LinkUMona',"Monat");
define('KAL_LinkUWoch',"");
define('KAL_LinkUDrck','Drucken');
define('KAL_LinkUExpt',"Export");
define('KAL_LinkUSuch',"");
define('KAL_LinkUEing',"");
define('KAL_LinkUAend',"");
define('KAL_LinkULogi',"");
define('KAL_LinkULogx',"");
define('KAL_LnkOListN',false);
define('KAL_LnkOMonaN',false);
define('KAL_LnkOWochN',false);
define('KAL_LnkODrckN',false);
define('KAL_LnkOExptN',false);
define('KAL_LnkOSuchN',false);
define('KAL_LnkOEingN',false);
define('KAL_LnkOAendN',false);
define('KAL_LnkOLogiN',false);
define('KAL_LnkUListN',false);
define('KAL_LnkUMonaN',false);
define('KAL_LnkUWochN',false);
define('KAL_LnkUDrckN',false);
define('KAL_LnkUExptN',false);
define('KAL_LnkUSuchN',false);
define('KAL_LnkUEingN',false);
define('KAL_LnkUAendN',false);
define('KAL_LnkULogiN',false);

//Terminliste
define('KAL_Intervall','0');
define('KAL_NIntervall','0');
define('KAL_IvWerte','#074ACF@');
define('KAL_NIvWerte','#074ACF@');
define('KAL_IvExakt',false);
define('KAL_SucheBleibt',false);
define('KAL_SuchFilter',4);
define('KAL_SuchFltArchiv',false);
define('KAL_ListenLaenge',25);
define('KAL_ListenIndex',1);
define('KAL_Rueckwaerts',false);
define('KAL_ArchivRueckwaerts',true);
define('KAL_NaviOben',1);
define('KAL_NaviUnten',1);
define('KAL_NaviBild',true);
define('KAL_EigeneZeilen',false);
define('KAL_EigeneDruckZeilen',false);
define('KAL_Laufendes',false);
define('KAL_LfndEnde',true);
define('KAL_LfndZeit',true);
define('KAL_Aktuelles',true);
define('KAL_AktuEnde',true);
define('KAL_AktuZeit',true);
define('KAL_ListeVertikal','');
define('KAL_ListenInfo',3);
define('KAL_ListenInfTitel',"");
define('KAL_GastLInfo',true);
define('KAL_ListenErinn',-1);
define('KAL_ListenErinTitel',"");
define('KAL_GastLErinn',true);
define('KAL_ListenBenachr',-1);
define('KAL_ListenBenachTitel',"");
define('KAL_GastLBenachr',true);
define('KAL_ListenAendern',-1);
define('KAL_ListenAendTitel',"");
define('KAL_GastLAendern',false);
define('KAL_ListenKopieren',-1);
define('KAL_ListenKopieTitel',"");
define('KAL_GastLKopieren',true);
define('KAL_ListenAendKopieren',true);
define('KAL_NummerStellen',4);
define('KAL_TagesTrenner',0);
define('KAL_WochenTrenner',0);
define('KAL_MonatsTrenner',0);
define('KAL_MonatLLang',0);
define('KAL_ListenMemoLaenge',0);
define('KAL_DruckLMemoLaenge',0);
define('KAL_DruckLMailOffen',false);
define('KAL_DruckLMemo',true);
define('KAL_DruckLFarbig',false);
define('KAL_ErsatzBildKlein','');
define('KAL_LinkSymbol',true);
define('KAL_ListenKateg',true);
$kal_Kategorien=array("Kino"=>'A',"Theater"=>'B',"Sport"=>'C',"Freizeit"=>'D');
$kal_Symbole=array("rot"=>'A',"gelb"=>'B',"grün"=>'C');
define('KAL_SymbolTyp','jpg');
define('KAL_DetailPopup',false);
define('KAL_MailPopup',true);
define('KAL_NListeAnders',false);
define('KAL_NVerstecktSehen',false);

// Monatsblatt
define('KAL_MNaviOben',1);
define('KAL_MNaviUnten',1);
define('KAL_MNaviBild',true);
define('KAL_MSuchFilter',3);
define('KAL_MonatMLang',2);
define('KAL_MonWochNr',true);
define('KAL_MonTxNr','Nr.');
define('KAL_MonFremd',true);
define('KAL_MonOhneAltes',false);
define('KAL_MDatumsformat',1);
define('KAL_MLinkZiel',1); //0:Liste, 1:variabel, 2:Detail
define('KAL_MLinkLeerNeu',false);
define('KAL_MTerminDetail',true);
define('KAL_MEigenesLayout',false);
define('KAL_MTerminZahl',2);
define('KAL_MDetail1Fld',2);
define('KAL_MDetail2Fld',4);
define('KAL_MDetail3Fld',3);
define('KAL_MDetail4Fld',-1);
define('KAL_MDetail1Trn',' Uhr<br>');
define('KAL_MDetail2Trn','<br>');
define('KAL_MDetail3Trn','');
define('KAL_MDetailKuerzen',15);
define('KAL_MonatsKateg',false);
define('KAL_MonatsInfo',true);
define('KAL_GastMoInfo',true);
define('KAL_MonatsErinn',false);
define('KAL_GastMoErinn',false);
define('KAL_MonatsBenachr',false);
define('KAL_GastMoBenachr',false);
define('KAL_MonatsICal',false);
define('KAL_GastMoICal',false);
define('KAL_MonatsZusage',false);
define('KAL_GastMoZusage',false);
define('KAL_MonatZeigeZusage',false);
define('KAL_GastMZeigeZusage',false);
define('KAL_MonatsZusagZ',false);
define('KAL_GastMoZusagZ',false);
define('KAL_MonZusagZZeigeLeer',true);
define('KAL_MonZusagZErsatz','');
define('KAL_MonZusagZMuster','#R/#K frei');
define('KAL_MZellenHoehe',4);
define('KAL_WZellenHoehe',15);
define('KAL_DruckMFarbig',false);
define('KAL_EigeneMDruckZelle',false);

// Termindetail
define('KAL_EigeneDetails',false);
define('KAL_DetailNaviOben',1);
define('KAL_DetailNaviUnten',1);
define('KAL_DetailNaviBild',true);
define('KAL_ZeigeLeeres',true);
define('KAL_DetailInfo',6);
define('KAL_GastDInfo',true);
define('KAL_DetailErinn',-1);
define('KAL_GastDErinn',true);
define('KAL_DetailBenachr',-1);
define('KAL_GastDBenachr',true);
define('KAL_DetailAendern',-1);
define('KAL_GastDAendern',true);
define('KAL_DetailKopieren',-1);
define('KAL_GastDKopieren',true);
define('KAL_DetailDrucken',6);
define('KAL_EigeneDruckDetails',false);
define('KAL_GastDDrucken',true);
define('KAL_DruckDFarbig',false);
define('KAL_DruckDMailOffen',false);
define('KAL_MonatDLang',0);
define('KAL_DetailLinkSymbol',false);
define('KAL_DetailDateiSymbol',false);
define('KAL_DTitelQuelle',0);
define('KAL_DTitelWL',3);
define('KAL_DTitelZL',30);
define('KAL_ErsatzBildGross','');
define('KAL_NDetailAnders',false);

// Suchformular
define('KAL_SuchArchiv',false);
define('KAL_SuchIntervall',true);

// Termineintrag
define('KAL_Direkteintrag',false);
define('KAL_Direktaendern',0);
define('KAL_FormatCode',true);
define('KAL_PLZLaenge',5);
define('KAL_TCalPicker',true);
define('KAL_TCalYrScroll',false);
define('KAL_TimeStart',09.50);
define('KAL_TimeStopp',18.75);
define('KAL_TimeIvall',0.50);
define('KAL_EintragDSE1',true);
define('KAL_EintragDSE2',false);
define('KAL_Periodik',true);
define('KAL_MaxPeriode',365);
define('KAL_MaxWiederhol',52);
define('KAL_BildMaxKByte',55);
define('KAL_DateiMaxKByte',25);
define('KAL_ThumbBreit',90);
define('KAL_ThumbHoch',64);
define('KAL_BildResize',true);
define('KAL_DateiEndungen','php;php3;php5;pl;js');
define('KAL_DateiEndgPositiv',false);
define('KAL_BildBreit',480);
define('KAL_BildHoch',330);
define('KAL_VorschauRahmen',false);
define('KAL_VorschauBreit',90);
define('KAL_VorschauHoch',80);
define('KAL_EingabeTrenner','');
define('KAL_EintragAdminInfo',true);
define('KAL_EintragMail',false);
define('KAL_AendernMail',false);
define('KAL_FreischaltMail',true);
define('KAL_MailListeAdr','');
define('KAL_MailListeEintrag',false);
define('KAL_MailListeFreischalt',false);
define('KAL_MailListeAendern',false);
define('KAL_NutzerEMail',false);
define('KAL_NEingabeLogin',false);
define('KAL_NutzerListFeld',2);
define('KAL_NNutzerListFeld',2);
define('KAL_NAendernFremde',false);
define('KAL_NKopiereEigene',false);
define('KAL_NEingabeAnders',false);
define('KAL_EintragszeitNeu',false);
define('KAL_AendernMitLoeschen',true);
define('KAL_AendernLoeschArt',1);
define('KAL_AendernLschOnOff',true);
define('KAL_AendernOnOff',true);
define('KAL_AendernCaptcha',false);

// Infoformular
define('KAL_InfoNDetail',false);
define('KAL_InfoMitMemo',false);
define('KAL_NutzerInfoFeld',2);
define('KAL_InfoAbsPflicht',false);
define('KAL_InfoDSE1',true);
define('KAL_InfoDSE2',false);
define('KAL_ErinnernDSE1',false);
define('KAL_ErinnernDSE2',false);
define('KAL_NachrichtDSE1',false);
define('KAL_NachrichtDSE2',false);
define('KAL_InfoLink','');

// Kontaktformular
define('KAL_KontaktNDetail',false);
define('KAL_KontaktMitMemo',false);
define('KAL_NutzerKontaktFeld',2);
define('KAL_KontaktAbsPflicht',false);
define('KAL_KontaktDSE1',false);
define('KAL_KontaktDSE2',false);
define('KAL_KontaktLink','');

// Google-Maps
define('KAL_GMapSource','O'); // O: OSM oder G: GoogleMap
define('KAL_GMapV3',true);
define('KAL_GMapURL','http://maps.google.com/maps/api/js?sensor=false&language=de');
define('KAL_GMapCode','#??????');
define('KAL_GMapTypeControl',true);
define('KAL_SMapCode','');
define('KAL_SMapTypeControl',false);
define('KAL_SMap2Finger',true);
define('KAL_GMapBreit',320);
define('KAL_GMapHoch',225);
define('KAL_GMapWarten',3);
define('KAL_GMapBZentr',51.050);
define('KAL_GMapLZentr',10.410);
define('KAL_GMapZoom',5);

//Benutzerverwaltung
$kal_NutzerFelder=array("Nummer","Session","aktiv","Benutzer","Passwort","E-Mail","Anrede","Vorname + Name","PLZ Ort","Strasse","Telefon, Mobil");
$kal_NutzerPflicht=array(0,0,0,1,1,1,0,1,1,0,0);
define('KAL_SessionZeit',45);
define('KAL_NutzerNeuErlaubt',true);
define('KAL_NutzerDSE1',true);
define('KAL_NutzerDSE2',false);
define('KAL_NutzerAendern',true);
define('KAL_PasswortSenden',true);
define('KAL_NutzerZentrum',true);
define('KAL_NutzerZentrSel',true);
define('KAL_NutzerNeuAdmMail',true);
define('KAL_NutzerNeuMail',true);
define('KAL_NutzerAendAdmMail',true);
define('KAL_NutzerAktivMail',true);
define('KAL_FreischaltAdmin',false);
define('KAL_FreischaltWin','Freischalt');
define('KAL_ErinnOkMail',false);
define('KAL_BenachrOkMail',false);
define('KAL_FreischaltNeuMail',true);
define('KAL_ErinnNDetail',false);
define('KAL_ErinnMitMemo',false);
define('KAL_NutzerErinnFeld',2);
define('KAL_ErinnLink','');
define('KAL_BenachrNDetail',false);
define('KAL_BenachrMitMemo',false);
define('KAL_NutzerBenachrFeld',2);
define('KAL_BenachrLink','');
define('KAL_LoginCaptcha',true);

//iCal-Export
define('KAL_ListenCal',-1);
define('KAL_GastLCal',true);
define('KAL_TxListenCalTitel','');
define('KAL_DetailCal',-1);
define('KAL_GastDCal',true);
define('KAL_TxCalZeile','exportieren');
define('KAL_TxCalIcon','Termin übernehmen');
define('KAL_CalTZID','Europe/Berlin');
define('KAL_ICalName','Termin');
define('KAL_ICalNamNr',true);
define('KAL_CalDTSTART',1);
define('KAL_CalDTEND',0);
define('KAL_CalZTSTART',0);
define('KAL_CalZTEND',0);
define('KAL_CalGanzTag',8);
define('KAL_CalStdDauer',2);
define('KAL_CalSUMMARY',0);
define('KAL_CalSUMMARY2',0);
define('KAL_CalBindeSUMMA','');
define('KAL_CalDESCRIPTION',0);
define('KAL_CalDESCRIPTION2',0);
define('KAL_CalBindeDESCR','');
define('KAL_CalLenDESCR',0);
define('KAL_CalCATEGORIES',0);
define('KAL_CalORGANIZER',0);
define('KAL_CalLOCATION',0);
define('KAL_CalLOCATION2',0);
define('KAL_CalBindeLOCAT',' ');
define('KAL_CalGEO',0);
define('KAL_CalURL','');
define('KAL_CalATTACH',0);
define('KAL_CalDTSTAMP',0);
define('KAL_CalCREATED',-1);
define('KAL_CalMODIFIED',-1);
define('KAL_CalSTATUS','');
define('KAL_CalCLASS','PUBLIC');
define('KAL_CalTRANSP','');
define('KAL_CalSSLExp',false);
define('KAL_CalSSLUrl',false);
define('KAL_CalPopup',true);
define('KAL_CalPopupBreit',550);
define('KAL_CalPopupHoch',500);
define('KAL_CalPopupX',10);
define('KAL_CalPopupY',5);

// Vorschau-Box (Ajax)
define('KAL_VBoxMon',true);
define('KAL_VBoxAutoAus',false);
define('KAL_VBoxWarten',800);
define('KAL_VBoxFelder','0,1,2,4,3,0');
define('KAL_VBoxNFelder','0,1,2,4,3,0');
define('KAL_VBoxLinkFld','0,1,0,0,0,0');
define('KAL_VBoxFldStil',',,,,,');
define('KAL_VBoxEigenesLayout',false);
define('KAL_VBoxNrStellen',1);
define('KAL_VBoxTxNr','Nummer');
define('KAL_VBoxLeeres',false);
define('KAL_VBoxWidth',385);
define('KAL_VBoxHeight',220);
define('KAL_VBoxHOffset',0);
define('KAL_VBoxVOffset',0);
define('KAL_VBoxInfo',5);
define('KAL_VBoxGastInfo',true);
define('KAL_VBoxErinn',-1);
define('KAL_VBoxGastErinn',false);
define('KAL_VBoxBenachr',-1);
define('KAL_VBoxGastBenachr',false);
define('KAL_VBoxDruck',-1);
define('KAL_VBoxGastDruck',false);
define('KAL_VBoxICal',-1);
define('KAL_VBoxGastICal',false);
define('KAL_VBoxZusage',-1);
define('KAL_VBoxGastZusage',false);
define('KAL_VBoxZeigeZusage',false);
define('KAL_VBoxGastZeigeZusage',false);
define('KAL_VBoxZusagZ',-1);
define('KAL_VBoxGastZusagZ',false);
define('KAL_VBoxTxZusagZ','Zusageninfo');
define('KAL_VBoxTxZusagZMuster','#Z von #K gebucht, #R Plätze frei');
define('KAL_VBoxLink',"");
define('KAL_NutzerVBoxFld',0);
define('KAL_NNutzerVBoxFld',0);

//MiniKalender
define('KAL_MiniMonate',2);
define('KAL_MiniReihen',1);
define('KAL_MiniLink',"");
define('KAL_MiniTarget',"kalender");
define('KAL_MiniSicht',1);
define('KAL_MiniPopup',false);
define('KAL_MiniTextFeld',1);
define('KAL_MiniTextFld2',0);
define('KAL_MiniWochenNr',false);
define('KAL_MiniTxWo','Wo');
define('KAL_MiniTxNr','Nr');
define('KAL_MiniOhneAltes',false);
define('KAL_MiniVertikal',true);
define('KAL_MiniFremd',false);

// Zusatzmodul Zusagesystem
define('KAL_ZusageSystem',false);
define('KAL_ZUser','Demo');
define('KAL_ZCode','');
define('KAL_ZusageFelder','Nummer;Termin-Nr;Datum;Uhrzeit;Veranstaltung;Buchung;aktiv;Benutzer;E-Mail;ANZAHL;Anrede;Name;PLZ Ort;Straße;Telefon, Fax');
define('KAL_ZusageFeldTyp','i;i;d;z;t;@;t;n;e;n;t;t;t;t;t');
define('KAL_ZusageAuswahl',';;;;;;;;;;;;;;');
define('KAL_ZusageQuellen','0;0;0;0;0;0;0;0;0;0;0;0;0;0;0');
define('KAL_ZusagePflicht','1;1;1;0;1;1;0;0;1;1;0;1;1;0;0');
define('KAL_ZusageLstFeld','0;0;1;2;0;0;0;0;0;5;0;3;4;0;0');
define('KAL_NZusageLstFld','0;0;1;2;3;0;4;0;7;8;0;5;6;0;0');
define('KAL_ZusageListAdm','1;1;2;0;3;4;5;0;6;0;0;0;0;0;0');
define('KAL_ZusageExptAdm','0;0;1;2;3;0;4;0;7;8;0;5;6;0;0');
define('KAL_ZusageDrckAdm','0;0;1;2;3;0;4;0;7;8;0;5;6;0;0');
define('KAL_ZusageFrmFeld','0;0;1;2;3;0;0;0;4;5;6;7;8;9;10;11;12;13;14;15;16;17;18;19;20');
define('KAL_DirektZusage',0);
define('KAL_EinKlickLZusage',false);
define('KAL_EinKlickDZusage',false);
define('KAL_LoeschKlickZusage',false);
define('KAL_LoeschGastZusage',true);
define('KAL_LoeschNutzerZusage',false);
define('KAL_KeineDoppelBuchung',false);
define('KAL_ZusageFrist',2);
define('KAL_ZusageBisEnde',false);
define('KAL_PruefeZusageKapaz',true);
define('KAL_Pruefe1KlickKapaz',false);
define('KAL_ZusageVormerkErlaubt',false);
define('KAL_ZusageVormerkTxtZeile',false);
define('KAL_RechneZusagePreis',true);
define('KAL_SperreZusagePreis',true);
define('KAL_ErlaubeZusageNull',false);
define('KAL_ZusageSelectAnzahl',true);
define('KAL_ZusageNamentlich',false);
define('KAL_ZusageMaxNamenOhneKapaz',5);
define('KAL_ZusageMaxNamenMitKapaz',20);
define('KAL_ZusagePopup',false);
define('KAL_ZusageDSE1',false);
define('KAL_ZusageDSE2',false);
define('KAL_ListenZusage',5);
define('KAL_GastLZusage',true);
define('KAL_ListenZusagZ',-1);
define('KAL_GastLZusagZ',true);
define('KAL_ListenZusagZLeer','-');
define('KAL_ListenZusagRLeer','');
define('KAL_ListeZeigeZusage',true);
define('KAL_GastLZeigeZusage',true);
define('KAL_ListenZusagS',-1);
define('KAL_GastLZusagS',true);
define('KAL_ZusageStatusRot',2);
define('KAL_ZusageStatusGlb',8);
define('KAL_ZusageStatusSchwelle',false);
define('KAL_DetailZusagS',false);
define('KAL_DetailZusagKLeer','');
define('KAL_DetailZusagRLeer','');
define('KAL_DetailZeigeZusage',true);
define('KAL_GastDZeigeZusage',true);
define('KAL_ZeigeZusageEml',false);
define('KAL_DetailZusage',4);
define('KAL_GastDZusage',true);
define('KAL_MonatsZusagS',false);
define('KAL_GastMoZusagS',false);
define('KAL_MonZusageHG',false);
define('KAL_MonZusagHGBl','Det');
define('KAL_Zusagen',false);
define('KAL_Zusage','zusagen.txt');
define('KAL_SqlTabZ','kal_zusagen');
define('KAL_ZusageLink','');
define('KAL_TerminDatumFeld',1);
define('KAL_TerminZeitFeld',2);
define('KAL_TerminVeranstFeld',0);
define('KAL_ZusageVeranstLaenge',100);
define('KAL_ZusageNameFrist','zusagen bis');
define('KAL_ZusageNameAnzahl','Anzahl');
define('KAL_ZaehleAktiveZusagen',false);
define('KAL_ZusageNameKapaz','Plätze');
define('KAL_ZusageKapazVersteckt',true);
define('KAL_ZusageFormMitListe',true);
define('KAL_GastZusageFormMitL',true);
define('KAL_ZusageListeStatus',0);
define('KAL_ZusageAdmRueckw',false);
define('KAL_ZusageAdmLstVstBreit',50);
define('KAL_ZusageAdmLstLaenge',25);
define('KAL_ZusageAdmLstKommend',true);
define('KAL_ZusageAdmLstVorbei',true);
define('KAL_ZusageAdmDrKonf',true);
define('KAL_ZentrumEigeneZusage',true);
define('KAL_ZentrumFremdeZusage',true);
define('KAL_ZusageLstFilter',0);
define('KAL_ZusageEintragMail',true);
define('KAL_ZusageAendernMail',false);
define('KAL_ZusageFreigabeMail',true);
define('KAL_ZusageNeuInfoAut',true);
define('KAL_ZusageBstInfoAut',true);
define('KAL_ZusageAendInfoAut',true);
define('KAL_FormAendZusageInfo',true);
define('KAL_ZusageLschInfoAut',true);
define('KAL_ZusageAendEigene',true);
define('KAL_ZusageLschEigene',true);
define('KAL_ZusageLschNzZusag',true);
define('KAL_ZusageNeuInfoAdm',true);
define('KAL_ZusageBstInfoAdm',true);
define('KAL_ZusageAendInfoAdm',true);
define('KAL_ZusageLschInfoAdm',true);
define('KAL_ZusageVmkInfoVorbei',false);
define('KAL_ZusageMaxKapInfoAdm',false);
define('KAL_ZusageGrenzeInfoAdm',false);
define('KAL_ZusageMaxKapInfoAut',false);
define('KAL_ZusageGrenzeInfoAut',false);
define('KAL_ZusageAAendInfoZs',false);
define('KAL_ZusageAAendInfoAu',false);

//aktuelle Termine
$kal_AktuelleFeld=array(0,1,2,0,3,0);
$kal_AktuelleLink=array(0,1,0,0,1,0);
$kal_AktuelleStil=array('','','','','font-weight:bold;','');
define('KAL_AktuelleAnzahl',3);
define('KAL_AktuelleTage',0);
define('KAL_AktuelleTagLfd',true);
define('KAL_AktuelleIndex',1);
define('KAL_AktuelleRueckw',false);
define('KAL_AktuelleEnde',true);
define('KAL_AktuelleZeit',false);
define('KAL_AktuelleNotErsatz',false);
define('KAL_AktuelleLink',"");
define('KAL_AktuelleTarget',"kalender");
define('KAL_AktuellePopup',false);
define('KAL_AktuelleKopf',true);
define('KAL_AktuelleKpfWdh',false);
define('KAL_AktuelleAbstand',0);
define('KAL_AktuelleEigeneZeilen',false);
define('KAL_AktuelleJahrhundert',false);
define('KAL_AktuelleMitWochentag',1);

//laufende Termine
$kal_LaufendeFeld=array(0,1,2,0,3,0);
$kal_LaufendeLink=array(0,1,0,0,1,0);
$kal_LaufendeStil=array('','','','','font-weight:bold;','');
define('KAL_LaufendeEnde',true);
define('KAL_LaufendeZeit',false);
define('KAL_LaufendeLink',"");
define('KAL_LaufendeIndex',1);
define('KAL_LaufendeRueckw',false);
define('KAL_LaufendeNotErsatz',false);
define('KAL_LaufendeTarget',"kalender");
define('KAL_LaufendePopup',true);
define('KAL_LaufendeKopf',true);
define('KAL_LaufendeKpfWdh',false);
define('KAL_LaufendeAbstand',0);
define('KAL_LaufendeEigeneZeilen',false);
define('KAL_LaufendeJahrhundert',false);
define('KAL_LaufendeMitWochentag',0);

//neue Termine
$kal_NeueFeld=array(0,1,2,0,3,0);
$kal_NeueLink=array(0,1,0,0,1,0);
$kal_NeueStil=array('','','','','font-weight:bold;','');
define('KAL_NeueAnzahl',5);
define('KAL_NeueFrist',0);
define('KAL_NeueNachId',true);
define('KAL_NeueKommend',true);
define('KAL_NeueIndex',1);
define('KAL_NeueRueckw',false);
define('KAL_NeueEnde',true);
define('KAL_NeueZeit',true);
define('KAL_NeueLink',"");
define('KAL_NeueTarget',"_blank");
define('KAL_NeuePopup',true);
define('KAL_NeueKopf',true);
define('KAL_NeueKpfWdh',false);
define('KAL_NeueAbstand',0);
define('KAL_NeueEigeneZeilen',false);
define('KAL_NeueJahrhundert',false);
define('KAL_NeueMitWochentag',1);

// RSS-Feed
define('KAL_RssFelder','1;2;0;4;3;0;0;0;0');
define('KAL_RssTrenner','": ";" ";",";""');
define('KAL_RssLink','');
define('KAL_RssIntervall','A');
define('KAL_RssAbHeute',true);
define('KAL_RssMitEnde',true);
define('KAL_RssMitZeit',true);
define('KAL_RssAnzahl',5);
define('KAL_RssSortFeld',1);
define('KAL_RssRueckw',false);
define('KAL_RssFilter','"0";"";"";"";"0";"";"";""');
define('KAL_RssSprache','de-de');
define('KAL_RssZeichensatz',0);
define('KAL_RssBBFormat',2);

/* Sprachfloskeln */
// Kürzel
define('KAL_TxSymbJhr','JJ');
define('KAL_TxSymbMon','MM');
define('KAL_TxSymbTag','TT');
define('KAL_TxSymbUhr','hh:mm');
$kal_WochenTag=array("So","Mo","Di","Mi","Do","Fr","Sa");
define('KAL_TxKMonate','Jan.;Feb.;März;Apr.;Mai;Juni;Juli;Aug.;Sept.;Okt.;Nov.;Dez.');
define('KAL_TxLMonate','Januar;Februar;März;April;Mai;Juni;Juli;August;September;Oktober;November;Dezember');
define('KAL_TxJa','Ja');
define('KAL_TxNein','Nein');
define('KAL_TxUnd','und');
define('KAL_TxOder','oder');
define('KAL_TxVon','von');
define('KAL_TxAm','am');
define('KAL_TxIm','im');
define('KAL_TxBis','bis');
define('KAL_TxWie','wie');
define('KAL_TxIst','ist');
define('KAL_TxBzwAb','bzw. ab');
define('KAL_TxAberNicht','aber nicht wie');
define('KAL_TxNicht','nicht');
define('KAL_TxAktiv','aktiviert');

// Terminliste
define('KAL_TxAlle','alle');
define('KAL_TxTermin','Termin');
define('KAL_TxTermine','Termine');
define('KAL_TxTag','Tag');
define('KAL_TxTage','Tage');
define('KAL_TxWoche','Woche');
define('KAL_TxDeklWo','');
define('KAL_TxWochen','Wochen');
define('KAL_TxMonat','Monat');
define('KAL_TxDeklMo','r');
define('KAL_TxMonate','Monate');
define('KAL_TxQuartal','Quartal');
define('KAL_TxDeklQu','s');
define('KAL_TxHalbJahr','Halbjahr');
define('KAL_TxDeklHJ','s');
define('KAL_TxJahr','Jahr');
define('KAL_TxDeklJh','s');
define('KAL_TxDiese','diese');
define('KAL_TxNaechste','nächste');
define('KAL_TxVorige','vorige');
define('KAL_TxTerminKommt','kommende Termine');
define('KAL_TxTerminVorbei','abgelaufene Termine');
define('KAL_TxArchiv','Terminarchiv');
define('KAL_TxMitArchiv','mit Archiv');
define('KAL_TxSeite','Seite');
define('KAL_TxNr',"Nr.");
define('KAL_TxSortieren','sortieren');
define('KAL_TxAufsteigend','aufsteigend ');
define('KAL_TxAbsteigend','absteigend ');
define('KAL_TxDatei','Datei');
define('KAL_TxAnfang','Anfang');
define('KAL_TxEnde','Ende');
define('KAL_TxSuchen','Suchen');
define('KAL_TxListGsmt',"Gesamtliste");
define('KAL_TxListSuch',"Suchergebnis für #S");
define('KAL_TxSuchMeld','Stellen Sie Ihre Suchanfrage zusammen!');
define('KAL_TxAMetaTit',"Kalender");
define('KAL_TxAMetaKey',"Termine Veranstaltungen");
define('KAL_TxAMetaDes',"Veranstaltungskalender");
define('KAL_TxLMetaTit',"Terminliste");
define('KAL_TxLMetaKey',"Termine Veranstaltungen");
define('KAL_TxLMetaDes',"Terminliste");
define('KAL_TxKontakt','Kontakt');
define('KAL_TxSendInfo','Information versenden');

// Monatsblatt
define('KAL_TxMonGsmt',"Gesamtliste für Monat #M #Y");
define('KAL_TxMonSuch',"Suchergebnis für #S Monat #M #Y");
define('KAL_TxMMetaTit',"Kalender im #M");
define('KAL_TxMWochNr','#W.<br />Wo');
define('KAL_TxMMetaKey',"Termine Veranstaltungen #M #Y");
define('KAL_TxMMetaDes',"Veranstaltungskalender Monat #M");

// Wochenblatt
define('KAL_TxWocGsmt',"Gesamtliste für Woche #W #Y");
define('KAL_TxWocSuch',"Suchergebnis für #S Woche #W #Y");
define('KAL_TxWMetaTit',"Kalender in Woche #W");
define('KAL_TxWMetaKey',"Termine Veranstaltungen Woche #W #Y");
define('KAL_TxWMetaDes',"Veranstaltungskalender Woche #W #Y");

// Termindetails
define('KAL_TxDetails',"Informationen zum Termin #");
define('KAL_TxDetail','Termindetails');
define('KAL_TxDMetaTit',"Termindetail");
define('KAL_TxDMetaKey',"Veranstaltungsdetails Termineinzelheiten");
define('KAL_TxDMetaDes',"Veranstaltungsdetails");
define('KAL_TxDrucken','drucken');
define('KAL_TxKeinDatensatz','Datensatz # nicht gefunden!');
define('KAL_TxNummer',"Nummer");
define('KAL_TxInfoSenden',"Info senden");
define('KAL_TxErinServ','Erinnerung');
define('KAL_TxBenachServ','Benachrichtigung');
define('KAL_TxErinnService',"Erinnerung anfordern");
define('KAL_TxBenachrService',"Benachrichtigung anfordern");
define('KAL_TxKontaktSenden',"Kontakt aufnehmen");
define('KAL_TxZumAnfang','rückwärts blättern');
define('KAL_TxZumEnde','vorwärts blättern');
define('KAL_TxAutor0000','Gast');
define('KAL_TxAutorUnbekannt','unbekannt');
define('KAL_TxUhr','Uhr');
define('KAL_TxGMapOrt','Veranstaltungsort');
define('KAL_TxGMap1Warten',"Karte wird geladen......");
define('KAL_TxGMap2Warten',"anderenfalls hier klicken");
define('KAL_TxKeinDetail','HTML-Schablone <i>kalDetail.htm</i> fehlt!');

// Suchformular
define('KAL_TxSuchIntervall','Suchintervall');
define('KAL_TxSondersuche','Sondersuche');
define('KAL_TxKeinAnderesDatum','sofern kein anderes\n Datum angegeben');

// Eingabeformular
define('KAL_TxEingabe','Eintragen');
define('KAL_TxTerminAendern','Termin ändern');
define('KAL_TxTerminFremd','fremden');
define('KAL_TxTerminEigen','eigenen');
define('KAL_TxPflicht','Pflichtfeld');
define('KAL_TxFormat','Format');
define('KAL_TxStatus','Status');
define('KAL_TxOnline','online/sichtbar');
define('KAL_TxOffline','offline/unsichtbar');
define('KAL_TxJNLeer','leer lassen');
define('KAL_TxVormerk','wartet auf Freigabe');
define('KAL_TxImmer','immer');
define('KAL_TxEinmal','einmalig');
define('KAL_TxTaegig','täglich');
define('KAL_TxWoechig','wöchentlich');
define('KAL_Tx14Taegig','14-tägig');
define('KAL_TxInJedem','in jedem');
define('KAL_TxMonatig','monatlich');
define('KAL_TxJaehrlich','jährlich');
define('KAL_TxLetzten','letzten');
define('KAL_TxVorLetzten','vorletzten');
define('KAL_TxSelbenDatum','selben Datum');
define('KAL_TxTagDesMonat','Tag des Monats');
define('KAL_TxTagDesJahres','im Jahr');
define('KAL_TxInsgesamt','insgesamt');
define('KAL_TxBisZum','bis zum');
define('KAL_TxMale','weitere Male');
define('KAL_TxNutzerRegel','(4...25 Zeichen)');
define('KAL_TxPassRegel','(4...16 Zeichen)');
define('KAL_TxPassHilfe','(zum Termin)');
define('KAL_TxStellen','Stellen');
define('KAL_TxKopieren','kopieren');
define('KAL_TxLoeschen','löschen');
define('KAL_TxKoordinaten','Koordinaten bearbeiten');
define('KAL_TxCaptchaFeld','Sicherheitscode');
define('KAL_TxCaptchaNeu','neues #Captcha anfordern');
define('KAL_TxZahlenCaptcha','Zahlen-');
define('KAL_TxTextCaptcha','Text-');
define('KAL_TxGrafikCaptcha','Grafik-');
define('KAL_TxCaptchaHilfe','Bitte den Buchstaben und die 4 Ziffern übertragen');
define('KAL_TxCaptchaFehl','Bitte geben Sie den Sicherheitscode korrekt ein!');
define('KAL_TxEingabeMeld','Tragen Sie jetzt Ihren neuen Termin ein!');
define('KAL_TxEingabeErfo','Der Termin wurde eingetragen und veröffentlicht!');
define('KAL_TxEingabeOffl',"Der Termin wurde eingetragen aber nicht veröffentlicht!");
define('KAL_TxVormerkErfo','Der Termin wurde vorgemerkt und der Webmaster informiert!');
define('KAL_TxEingabeFehl','Ergänzen Sie bei den rot markierten Feldern!');
define('KAL_TxBildTyp','Bilder mit der Endung # sind nicht erlaubt!');
define('KAL_TxBildGroesse','Bilder über # KByte werden nicht verarbeitet!');
define('KAL_TxDateiTyp','Dateien vom Typ # sind nicht erlaubt!');
define('KAL_TxDateiGroesse','Dateien über # KByte werden nicht gespeichert!');
define('KAL_TxBildOeffnen','Das Bild # konnte nicht geöffnet werden!');
define('KAL_TxEintragAdminBtr',"neuer Kalendereintrag Nr. #");
define('KAL_TxAendernAdminBtr',"geaenderter Kalendereintrag Nr. #");
define('KAL_TxEintragAdminTxt','Im Kalender wurde folgender Eintrag #N vorgenommen:\n \n #D');
define('KAL_TxEintragBtr','Re: Ihr Kalendereintrag bei #');
define('KAL_TxAendernBtr',"Re: Ihr geänderter Kalendereintrag bei #");
define('KAL_TxEintragTxt','Ihr Eintrag im Kalender bei #A wurde mit folgenden Daten entgegengenommen:\n \n #D\n \n Vielen Dank!');
define('KAL_TxFreischaltBtr','Re: Kalendereintrag bei # freigeschaltet');
define('KAL_TxFreischaltTxt','Ihr Eintrag im Kalender bei #A wurde mit folgenden Daten freigeschaltet:\n \n #D');
define('KAL_TxMailListeBtr','');
define('KAL_TxMailLstBtrAend',"geänderter Kalendereintrag bei #");
define('KAL_TxMailListeTxt','');
define('KAL_TxKopiereMeld','Kopieren Sie diesen Termin auf ein neues Datum!');
define('KAL_TxKopiereErfo','Die Terminkopie wurde eingetragen und veröffentlicht!');

//Änderungsformular
define('KAL_TxAendern','Ändern');
define('KAL_TxTerminNr','Terminnummer');
define('KAL_TxNummerFehlt','Bitte geben Sie die laufende Terminnummer an!');
define('KAL_TxNummerUnbek','Datensatz nicht gefunden! Bitte geben Sie eine gültige Nummer an!');
define('KAL_TxNummerPassw','Bitte geben Sie das korrekte Passwort zum Termin an!');
define('KAL_TxNummerFremd','Dieser Termin gehört nicht Ihnen! Bitte wählen Sie einen gültigen Termin!');
define('KAL_TxAendereZuAlt','Dieser Termin kann nicht mehr geändert werden!');
define('KAL_TxAendereMeld','Ändern Sie jetzt diesen Termin ab!');
define('KAL_TxKeineAenderung','Die Daten bleiben unverändert.');
define('KAL_TxAendereErfo','Die geänderten Termindaten wurden eingetragen!');
define('KAL_TxAendereVmk','Die Änderungen wurden vorgemerkt und der Webmaster informiert!');
define('KAL_TxNummerHilfe','Die Terminnummer erfahren Sie (sofern sonst nirgends erkennbar) aus der Adresszeile Ihres Browsers nach Aufruf der Detailansicht zum Termin.');
define('KAL_TxLoeschFrage','Wollen Sie den markierten Termin wirklich löschen?');
define('KAL_TxLoeschErfol','Der markierte Termin wurde gelöscht!');
define('KAL_TxLoescheFrag','Wollen Sie die markierten Termine wirklich löschen?');
define('KAL_TxLoescheErfo','Die markierten Termine wurden gelöscht!');

// Infoformular und Kontaktformular
define('KAL_TxSenden','Senden');
define('KAL_TxEmpfaenger','Empfänger');
define('KAL_TxAbsender','Absender');
define('KAL_TxInfoAbsender',"");
define('KAL_TxKontaktAbsender',"");
define('KAL_TxBetreff','Betreff');
define('KAL_TxMitteilung','Mitteilung');
define('KAL_TxInfoLink','der Link lautet');
define('KAL_TxInfoMeld','Informieren Sie einen Bekannten über diesen Termin!');
define('KAL_TxMailMeld','Treten Sie mit dem Verfasser des Termins in Kontakt!');
define('KAL_TxSendeErfo','Die Information wurde soeben versandt!');
define('KAL_TxSendeFehl','Die Nachricht konnte soeben nicht versandt werden!');
define('KAL_TxMailAn',"Verfasser des Termins");
define('KAL_TxInfoBtr',"interessanter Termin");
define('KAL_TxMailBtr',"Re: Ihr Termineintrag");
define('KAL_TxInfoTxt','Hallo,\n \n unter der Adresse # habe ich einen interessanten Termin gefunden. Unten der Link und ein Auszug.\n \n Mit freundlichen Grüßen');
define('KAL_TxMailTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter der Adresse #A einen Termin für den #D veröffentlicht. Zu diesem Termin interessiert mich ...\n \n Mit freundlichen Grüßen');

//Erinnerungsformular und Benachrichtigungsformular
define('KAL_TxErinnZeit','Erinnerungs-\n zeitpunkt');
define('KAL_TxVorBeginn','vor dem Veranstaltungsbeginn');
define('KAL_TxErinnMeld','Fordern Sie eine Erinnerung kurz vor Veranstaltungsbeginn an.');
define('KAL_TxErinnVorbei','Es sind keine Erinnerungstermine in der Vergangenheit möglich.');
define('KAL_TxErinnErfo','Ihr Erinnerungswunsch wurde vorgemerkt.');
define('KAL_TxErinnOkBtr',"Re: Terminerinnerung bei # vorgemerkt");
define('KAL_TxErinnOkTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A eine Terminerinnerung angefordert. Diese wird am #T zu folgendem Termin erfolgen:\n \n #D\n \n Mit freundlichen Grüßen');
define('KAL_TxErinnUnbekannt','# ist für diesen Dienst noch nicht freigeschaltet.\n Sie können jetzt die Freischaltung anfordern.');
define('KAL_TxErinnUnmoegl','# ist für diesen Dienst nicht vorgesehen.\n Wenden Sie sich an den Webmaster.');
define('KAL_TxErinnUnbkBtr',"Re: Terminerinnerungswunsch bei #");
define('KAL_TxErinnUnbkTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A eine Terminerinnerung angefordert.\n \n Ihre E-Mail-Adresse ist für diesen Dienst noch nicht freigeschaltet. Sie können diese Freischaltung erreichen, indem Sie jetzt den Link\n \n #L\n \n aufrufen.\n \n Mit freundlichen Grüßen');
define('KAL_TxErinnSendBtr',"Re: Terminerinnerung von #");
define('KAL_TxErinnSendTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A eine Terminerinnerung angefordert.\n \n #D\n \n Mit freundlichen Grüßen');
define('KAL_TxBenachrMeld','Fordern Sie eine Benachrichtigung bei Terminänderung an.');
define('KAL_TxBenachrVorbei','Es sind keine Benachrichtigungen in der Vergangenheit möglich.');
define('KAL_TxBenachrErfo','Ihr Benachrichtigungswunsch wurde vorgemerkt.');
define('KAL_TxBenachrOkBtr',"Re: Benachrichtigung bei # vorgemerkt");
define('KAL_TxBenachrOkTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A eine Benachrichtigung angefordert. Diese wird bei Veränderungen zu folgendem Termin erfolgen:\n \n #D\n \n Mit freundlichen Grüßen');
define('KAL_TxBenachrUnbekannt','# ist für diesen Dienst noch nicht freigeschaltet.\n Sie können jetzt die Freischaltung anfordern.');
define('KAL_TxBenachrUnmoegl','# ist für diesen Dienst nicht vorgesehen.\n Wenden Sie sich an den Webmaster.');
define('KAL_TxBenachrUnbkBtr',"Re: Benachrichtigungswunsch bei #");
define('KAL_TxBenachrUnbkTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A eine Benachrichtigung angefordert.\n \n Ihre E-Mail-Adresse ist für diesen Dienst noch nicht freigeschaltet. Sie können diese Freischaltung erreichen, indem Sie jetzt den Link\n \n #L\n \n aufrufen.\n \n Mit freundlichen Grüßen');
define('KAL_TxBenachrSendBtr',"Terminänderung bei #");
define('KAL_TxBenachrSendTxt','Sehr geehrte Damen und Herren,\n \n Sie haben unter #A eine Benachrichtigung erbeten, falls sich am folgenden Termin etwas verändert.\n \n #D\n \n Mit freundlichen Grüßen');
define('KAL_TxEMailFrei','E-Mail-Adresse freischalten');
define('KAL_TxEMailErfo','Ihre E-Mail-Adresse wurde freigegeben.\n Sie können jetzt Erinnerungen oder Benachrichtigungen anfordern.');

// Benutzerverwaltung
define('KAL_TxAnmelden','Anmelden');
define('KAL_TxBenutzer','Benutzer');
define('KAL_TxBenutzername','Benutzername');
define('KAL_TxGewuenscht','gewünschter');
define('KAL_TxMailAdresse','E-Mail-Adresse');
define('KAL_TxPasswort','Passwort');
define('KAL_TxNutzerNr','Benutzernummer');
define('KAL_TxBenutzerDat','Benutzerdaten');
define('KAL_TxNDatAendern','Benutzerdaten ändern');
define('KAL_TxNZentrum','Nutzerzentrum');
define('KAL_TxNZentrZeigen','Benutzerzentrum aufrufen');
define('KAL_TxNZentrStart',"Willkommen im Benutzerzentrum!");
define('KAL_LoginLogin','Zugang für registrierte Benutzer');
define('KAL_LoginNeu','Benutzerzugang jetzt beantragen');
define('KAL_LoginVergessen','vergessenes Passwort zusenden');
define('KAL_TxNutzerLogin','Melden Sie sich für die Kalenderbenutzung an!');
define('KAL_TxNutzerNamePass',"");
define('KAL_TxNutzerNameMail','Bitte Benutzernamen oder E-Mail-Adresse angeben!');
define('KAL_TxNutzerFalsch','Ein Benutzer mit diesen Daten ist nicht verzeichnet!');
define('KAL_TxNutzerPruefe','Prüfen und bestätigen Sie bitte Ihre Benutzerdaten!');
define('KAL_TxNutzerAendere','Ändern Sie jetzt die Benutzerdaten ab!'); //Adm
define('KAL_TxNutzerVergeben','Dieser Benutzername ist bereits vergeben!');
define('KAL_TxNutzerNeu','Die Benutzerdaten wurden eingetragen und der Webmaster informiert!');
define('KAL_TxNutzerGeaendert','Die geänderten Benutzerdaten wurden eingetragen!');
define('KAL_TxNutzerOK','Sie sind nun angemeldet und können die gewünschte Aktion ausführen.');
define('KAL_TxNutzerLogout','Sie wurden erfolgreich abgemeldet!');
define('KAL_TxNutzerSend','Die Zugangsdaten wurden soeben versandt!');
define('KAL_TxNutzerDatBtr',"Ihre Zugangsdaten");
define('KAL_TxNutzerDaten','Sehr geehrte Damen und Herren,\n \n Sie haben soeben Ihre Zugangsdaten zum Kalender auf #A angefordert. Diese lauten:\n \n lfd. Nummer: #N\n Benutzer: #B\n Passwort: #P');
define('KAL_TxNutzerNeuBtr',"Ihre Anmeldung");
define('KAL_TxNutzerNeuTxt','Ihre Anmeldung bei #A wurde registriert. Bitte bestätigen Sie die Anmeldung über den Link\n \n #L\n \n Hier Ihre Anmeldedaten:\n #D');
define('KAL_TxNutzNeuAdmBtr','neuer Kalender-Benutzer Nr. #');
define('KAL_TxNutzNeuAdmTxt','Ein neuer Kalender-Benutzer Nr. #N hat sich wie folgt angemeldet:\n \n #D');
define('KAL_TxNutzAendAdmBtr','geänderter Kalender-Benutzer Nr. #N');
define('KAL_TxNutzAendAdmTxt','Der Kalender-Benutzer Nr. #N hat seine Daten wie folgt geändert:\n \n #D');
define('KAL_TxNutzerAktivBtr',"Ihr Zugang wurde aktiviert");
define('KAL_TxNutzerAktivTxt','Sehr geehrte Damen und Herren,\n \n Ihr Benutzerzugang bei #A wurde soeben vom Webmaster freigeschaltet.');
define('KAL_TxAktivieren','Benutzerzugang jetzt aktivieren?');
define('KAL_TxAktiviert','Ihr Benutzerzugang wurde aktiviert!');
define('KAL_TxAktivFehl','Der Freischaltcode ist ungültig!');
define('KAL_TxDSE1',"Ich habe die [L]Datenschutzerklärung[/L] gelesen und stimme ihr zu.");
define('KAL_TxDSE2',"Ich bin mit der Verarbeitung und Speicherung<br />meiner persönlichen Daten im Rahmen der<br />Datenschutzerklärung einverstanden.");
define('KAL_TxSessionZeit','Die Sitzungszeit ist abgelaufen - bitte erneut anmelden!');
define('KAL_TxSessionUngueltig','Die Sitzung ist ungültig - bitte anmelden!');

//Nutzerzentrum-Erinnerungen
define('KAL_TxNeUebersicht','Erinnerungsübersicht');
define('KAL_TxNeUnveraendert','Die Erinnerungen bleiben unverändert.');
define('KAL_TxNeKeineErinn','Sie haben derzeit keine aktiven Erinnerungswünsche.');
define('KAL_TxNeLoeschen','Wollen Sie die #N markierten Erinnerungen wirklich löschen?');
define('KAL_TxNeGeloescht','#N Erinnerungen wurden gelöscht.');

//Nutzerzentrum-Benachrichtigungen
define('KAL_TxNnUebersicht','Benachrichtigungsübersicht');
define('KAL_TxNnUnveraendert','Die Benachrichtigungen bleiben unverändert.');
define('KAL_TxNnKeineBenachr','Sie haben derzeit keine aktiven Benachrichtigungswünsche.');
define('KAL_TxNnLoeschen','Wollen Sie die #N markierten Benachrichtigungen wirklich löschen?');
define('KAL_TxNnGeloescht','#N Benachrichtigungen wurden gelöscht.');

// Zusatzmodul Zusagesystem
define('KAL_TxListenZusageTitel','');
define('KAL_TxListenZusagZTitel','');
define('KAL_TxListenZusagZMuster','#Z/#K');
define('KAL_TxListenZusagSTitel','');
define('KAL_TxDetailZusagZMuster','');
define('KAL_TxZusageStatusRot','ausgebucht');
define('KAL_TxZusageStatusGlb','wenige Restplätze');
define('KAL_TxZusageStatusGrn','Plätze frei');
define('KAL_TxZusageIcon','reservieren');
define('KAL_TxZugesagtIcon','schon zugesagt, jetzt absagen');
define('KAL_TxZusageZeile','Reservierung');
define('KAL_TxZeigeZusageIcon','Zusagen zeigen');
define('KAL_TxZusage0Status','unbestätigt');
define('KAL_TxZusage2Status','noch nicht freigegeben');
define('KAL_TxZusage3Status','Widerruf vorgemerkt');
define('KAL_TxZusage4Status','Widerruf teilbestätigt');
define('KAL_TxZusage1Status','gültig');
define('KAL_TxZusage7Status','auf der Warteliste');
define('KAL_TxZusageAnzahl','Anzahl');
define('KAL_TxZusageMeld','Melden Sie sich jetzt für diese Veranstaltung an.');
define('KAL_TxZusageEintr','Vielen Dank! Ihre Zusage wurde vorgemerkt.');
define('KAL_TxZusageVormerk','Die Zusage wurde auf die Warteliste gesetzt.');
define('KAL_TxZusageVmkErlaubt','Sie können sich auf die Warteliste setzen lassen.');
define('KAL_TxZusageGeloescht','Ihre Zusage wurde widerrufen.');
define('KAL_TxZusageSperre','Keine Anmeldung mehr möglich!');
define('KAL_TxZusageKapazEnde','Die Veranstaltung ist bereits ausgebucht.');
define('KAL_TxKeineDoppelBuchung','Unter dieser E-Mail-Adresse wurde bereits früher zugesagt.');
define('KAL_TxZusageKapazRest','noch #R von #K Plätzen frei, #Z Zusagen bisher');
define('KAL_TxZusageKapazNull','bisher #Z Zusagen');
define('KAL_TxZusageEintrBtr','Ihre Terminzusage bei #A');
define('KAL_TxZusageEintrMTx','Hallo {Anrede} {Name},\n \n Sie haben soeben eine Zusage zu einem Termin unter #A vorgenommen. Diese Zusage müssen Sie über den folgenden Link bestätigen, ehe sie wirksam wird.\n #L\n \n Ihre Zusagedaten lauteten:\n #Z\n \n Sie betreffen den Termin:\n #D\n \n (automatische Nachricht)');
define('KAL_TxZusageAendBtr','Änderung Ihrer Terminzusage bei #A');
define('KAL_TxZusageAendMTx','Hallo {Anrede} {Name},\n \n Sie haben soeben Ihre Zusage zu einem Termin unter #A geändert.\n Diese Änderung müssen Sie über den folgenden Link bestätigen, ehe sie wirksam wird.\n #L\n \n Ihre Zusagedaten lauteten:\n #Z\n \n Sie betreffen den Termin:\n #D\n \n (automatische Nachricht)');
define('KAL_TxZusagenBisher','Bisher wurden folgende Zusagen gebucht:');
define('KAL_TxKeineZusagen','noch keine Zusagen zu diesem Termin eingetragen');
define('KAL_TxNzUebersicht','Übersicht eigener Zusagen');
define('KAL_TxNfUebersicht','Übersicht fremder Zusagen');
define('KAL_TxZusagenSuchen','Zusagen durchsuchen');
define('KAL_TxNfSuchErgebnis','Suchergebnis in Zusagen');
define('KAL_TxZusageDrckTit','aktuelle Zusagenübersicht');
define('KAL_TxZusageDrckTrm','{Datum} {Zeit}: {Veranstaltung}');
define('KAL_TxZusageDrckSum','#B Buchungen, #Z Zusagen bei #K Plätzen');
define('KAL_TxNzLoeschen','Wollen Sie die #N markierten Zusagen wirklich löschen?');
define('KAL_TxZusageLschFrueher','frühere Zusagen zu diesem Termin löschen');
define('KAL_TxZusageKeinFrueher','Es liegen keine früheren Zusagen von Ihnen vor.');
define('KAL_TxNzGeloescht','#N Zusagen wurden gelöscht.');
define('KAL_TxNzUnveraendert','Ihre Zusagen bleiben unverändert.');
define('KAL_TxNzZusageStat','Der Status der Zusage #N wurde geändert.');
define('KAL_TxNzZusageAenden','Ändern Sie jetzt die Zusagedetails.');
define('KAL_TxNzZusageAendOk','Die Zusage wurde geändert und der Webmaster informiert.');
define('KAL_TxZEinKlickEFrage','Zum Termin #T jetzt zusagen?');
define('KAL_TxZEinKlickLFrage','Die Zusage #Z jetzt löschen?');
define('KAL_TxZEinKlickLoesch','Die Zusage #Z wurde gelöscht.');
define('KAL_TxZusageBestaetigen','Terminzusage jetzt bestätigen?');
define('KAL_TxZusageBestaetTxt','die Zusage vom #Z\n für den Termin am #T\n zur Veranstaltung #V freischalten?');
define('KAL_TxZusageBestaetigt','Ihre Terminzusage wurde aktiviert!');
define('KAL_TxZusageWiderruf','Terminzusage jetzt widerrufen?');
define('KAL_TxZusageWdrrufTxt','die früheren Zusagen von #N\n zum Termin am #T\n zur Veranstaltung #V widerrufen?');
define('KAL_TxZusageIstWdrrufen','Ihre frühere Terminzusage wurde widerrufen!');
define('KAL_TxZusageBstCodeFehlt','Der Freischaltcode ist ungültig!');
define('KAL_TxZusageFreiBtr','Re: Terminzusage bei #A bestätigt');
define('KAL_TxZusageFreiMTx','Hallo {Anrede} {Name},\n \n Sie haben eine Zusage zu einem Termin unter #A eingetragen. Diese Zusage wurde soeben angenommen.\n \n Ihre Zusagedaten lauteten:\n #Z\n \n Sie betreffen den Termin:\n #D\n \n (automatische Nachricht)');
define('KAL_TxZusageInfoBtr','neue Terminzusage bei #A');
define('KAL_TxZusageInfoMTx','Unter #A wurde soeben eine neue Terminzusage eingetragen.\n \n Die Zusage lautet:\n #Z\n \n Sie betrifft den Termin:\n #D\n \n (automatische Nachricht)');
define('KAL_TxZusageAenABtr','Terminzusage bei #A geändert');
define('KAL_TxZusageAenAMTx','Unter #A wurde soeben eine Terminzusage geändert.\n \n Die neue Zusage lautete:\n #Z\n \n Sie betrifft den Termin:\n #D\n \n (automatische Nachricht)');
define('KAL_TxZusageMaxKapBtr','Zusagen bei #A voll ausgebucht');
define('KAL_TxZusageGrenzeBtr','Zusagenschwelle bei #A erreicht');
define('KAL_TxZusageMaxKapMTx','Unter #A wurde soeben eine Terminzusage verarbeitet.\n Damit ist die Grenze #N von #K Zusagen erreicht.\n \n Sie betraf den Termin:\n #D\n \n (automatische Nachricht)');
define('KAL_TxZusageLschBtr','Terminzusage bei #A gelöscht');
define('KAL_TxZusageLschMTx','Unter #A wurde soeben eine Terminzusage widerrufen.\n \n Die Zusage lautete:\n #Z\n \n Sie betraf den Termin:\n #D\n \n (automatische Nachricht)');
define('KAL_TxZusageVmkVorbeiBtr','Re: Ihre Zusage bei #A wurde hochgestuft');
define('KAL_TxZusageVmkVorbeiMTx','Ihre frühere Zusage bei #A wurde von der Warteliste genommen und hochgestuft. Sie sind jetzt verbindlich angemeldet.\n \n Die Zusage lautet:\n #Z\n \n Sie betrifft den Termin:\n #D');
define('KAL_TxZusageKontBtr','Re: Ihre Terminzusage bei #A');
define('KAL_TxZusageKontMTx','Sehr geehrte  ,\n \n Sie haben auf unserer Webseite #A am #Z eine Terminzusage zum Termin #D gemacht.....');
define('KAL_TxNZusageAlle','Nachricht an alle Zusager zu diesem Termin');
define('KAL_TxPlatzhZusage','Hinweis: Etwaige Platzhalter {#D} und {#Z} werden beim Senden ersetzt.');
define('KAL_TxNtUebersicht','Übersicht eigener Termine');

//iCal-Export
define('KAL_TxCalDownload','Download');
define('KAL_TxCalImport','Import');
define('KAL_TxCalGoogle','Google-Cal');
define('KAL_TxCalMeldExport','Datenaustausch im iCal-Format');
define('KAL_TxCalTxDnl','Nach dem Herunterladen können Sie die Termindaten durch Öffnen der Datei #D in den Kalender auf Ihrem Gerät übernehmen.');
define('KAL_TxCalTxExp','Durch den Kalenderimport kann der Termininhalt direkt in den Kalender auf Ihrem Gerät übernommen werden. Diese Funktion ist u.a. kompatibel mit Microsoft Outlook, Windows Kalender, Apple Kalender für iPhone und iPad (ab Version 4.x) und Apple iCal für OSx.');
define('KAL_TxCalTxGoogle','Übernahme des Termininhalts direkt in Ihren Google-Kalender');

// RSS-Feed
define('KAL_TxRssTitel','Kalender');
define('KAL_TxRssBeschreibung','aktuelle Termine');
define('KAL_TxRssUrheber','(c) Webmaster');

// BB-Formatleiste
define('KAL_TxBB_X','Schreiben Sie hier Ihren Text. Markieren Sie dann gewünschte Textpassagen und formatieren sie mit dem passenden Schalter.');
define('KAL_TxBB_B','fetterText: [b]Text[/b]');
define('KAL_TxBB_I','kursiver Text: [i]Text[/i]');
define('KAL_TxBB_U','unterstrichener Text: [u]Text[/u]');
define('KAL_TxBB_C','zentrierter Text: [center]Text[/center]');
define('KAL_TxBB_R','rechsbündiger Text: [right]Text[/right');
define('KAL_TxBB_E','Aufzählung: [list]Text[/list]');
define('KAL_TxBB_N','Numerierung: [list=o]Text[/list]');
define('KAL_TxBB_L','Link einfügen: [url]www.domain.de[/url] oder [url]www.domain.de Linktext[/url]');
define('KAL_TxBB_O','Schriftfarbe: [color=blue]Text[/color]');
define('KAL_TxBB_S','Schriftgröße: [size=+2]grosser Text[/size]');

// System-Fehler
define('KAL_TxSetupFehlt','Bitte zuerst das Setup/Update in der Administration ausführen!');
define('KAL_TxDateiRechte','Unzureichende Schreibrechte beim Speichern von #! (Setup-Fehler)');
define('KAL_TxSqlVrbdg','Entschuldigung - momentan MySQL-Verbindungsfehler');
define('KAL_TxSqlDaBnk','Entschuldigung - momentan MySQL-Datenbankauswahlfehler');
define('KAL_TxSqlFrage','Entschuldigung - momentan MySQL-Abfragefehler');
define('KAL_TxSqlEinfg','Entschuldigung - momentan MySQL-Einfügefehler');
define('KAL_TxSqlAendr','Entschuldigung - momentan MySQL-Änderungsfehler');
?>